### ISSUE TITLE
Visual Studio Project Import doesn't work.

### ISSUE THREAD

**Issue by ghost** [ZQuestClassic/ZQuestClassic#1]
That's right, they're missing quite a few stuff.
Mostly the new stuff such as the angelscript stuff and other new code files.

Gleeok has to fix this one, then I'll generate codeblocks projects.

**Comment by Gleeok** [comment]
We didn't add in angelscript yet because the binaries are quite large and is having to be updated to a bugfix version soon. I am debating on inlining the as source as well in case it needs to be modified. 

In the meantime you can download the latest from: http://www.angelcode.com/angelscript/

**Comment by ghost** [comment]
Did that ages ago.
No multiple inheritance, but there's a work around. So I can still make platypuses.

**Comment by Gleeok** [comment]
Should be fixed since revision 8.
