### ISSUE TITLE
@Gray: ZQuest Parser Crash - If Function Mismatch

### ISSUE THREAD

**Issue by ZoriaRPG** [ZQuestClassic/ZQuestClassic#106]
The parser crashes ZQuest if the user calls an internal function that it cannot find, or uses the wrong number of args for a valid function. 

If you for example, call, SetDMapScreenD(1,1,1,40) instead of Game->SetDMapScreenD(1,1,1,40), it crashes.

if you call, Game->SetDMapScreenD(1,1,40) --missing a value -- it crashes. 

The same occurs if you have a typo, such as Link->PressEc1. Crash, crash, crash. 
I believe that you rewrote ParseError.cpp, so you should look into this.

**Comment by ZoriaRPG** [comment]
Something similar is happening for improper setter/getter IDs:

http://timelord.insomnia247.nl/zc/zc_dev/ZQ_Compiler_Bug.png

**Comment by gwx** [comment]
Could you clarify what you mean about the setter/getter IDs?
