### ISSUE TITLE
Quest Files Can't Export Items

### ISSUE THREAD

**Issue by ywkls** [ZQuestClassic/ZQuestClassic#107]
Want to transfer items between quest files but not set up each and every one individually?

Well, too bad! No method currently exists that does this.

Mostly useful if you want to change tilesets, but keep similar items.

**Comment by evouga** [comment]
Obviously if you export items that use one tileset and import into a quest with a different tileset, the tile references in the item properties would be wrong and you'd have to go through and fix them (unless the item's placement on both tilesets is identical). I assume that's fine?

**Comment by ywkls** [comment]
That sounds like an acceptable compromise. I personally would use this mostly for things like their names and internal settings such as what type of item it was, whether it had a Link Tile Modifier, whether it used Magic or Rupees and possibly the script settings.

**Comment by evouga** [comment]
This is possible now in master.
