### ISSUE TITLE
Quest Sprite Settings Can't Be Exported?

### ISSUE THREAD

**Issue by ywkls** [ZQuestClassic/ZQuestClassic#108]
In the quest editor, under the menu Quest, go down to Graphics and Sprites.

The settings for Weapons/Misc can't be exported currently, to my knowledge.

I'm not sure how useful this would be, actually.  (Since the tiles would almost certainly be different between quests.) 

I guess it could let you retain the names and animation settings, along with their placement in the order they were in the original quest.

**Comment by evouga** [comment]
There is still some work I plan to do on how weapons are edited, but sprites can be exported now.
