### ISSUE TITLE
Upgrading Allegro for Playing Nice with Windows

### ISSUE THREAD

**Issue by lonegraywolf2000** [ZQuestClassic/ZQuestClassic#11]
In short: trying to use the allegro headers as is kind of sucks when using Visual Studio 2015. I'm not able to compile even ZC due to the use of version detection compared to feature detection (newer builds include the necessary headers).

I would like to upgrade to a higher version of Allegro (5.0.11 is the latest stable), but I need to know what sort of dangers there are in upgrading it. If it ends up being a problem, then that kind of puts my plans on using cmake on hold.

**Comment by Gleeok** [comment]
Perhaps a simple hack might work in this case. For example,  we could modify the allegro.h directly with #ifdef's, or perhaps even reintroduce the precompiled headers--precompiled.h  should always be included before anything else; even if generate precompiled headers is disabled (I stopped using them in zc myself).

ZC is really a mess, which is another reason I started using the semi-unity compilation build approach with MSVC. Does this not work for 2015 either? 

allegro 5 is sadly not compatible with 4 I'm afraid.

**Comment by vaualbus** [comment]
Maybye at this point the best think is to get rid of allegro and write our
engine. There has been so many problem with allegro. That would require a
lot of code unfortunally!

2016-02-04 11:04 GMT+01:00 Gleeok notifications@github.com:

**Comment by lonegraywolf2000** [comment]
@vaualbus There's always [SDL](https://www.libsdl.org/) if you'd rather switch engines.

@Gleeok I have not tried building the unity files yet. However, I suspect I'll run into the same issue. VS2015 defines types that Allegro tries to manually define in that version. For some reason, Allegro assumes that inttypes.h and stdint.h are not part of the headers included for MSVC (based on the platform file). Back in 2008, that was definitely true. However, that's no longer the case.

I can try messing with some things after work tonight. However...if Allegro 4.2's source states genuinely indicates that the header files I have are not being read in, then we have ourselves a situation where it's difficult for anyone using modern IDEs to use this.

**Comment by lonegraywolf2000** [comment]
Back home from work. Minor update. I tried building the stock project. Fails to build. Most of the errors deal with the redefined types from allegro as before. Two errors are from missing boost, and there was no mention of boost within the original vcproj files.

I am not downgrading Visual Studio, and I don't think others can. So, we need to confirm a few items.
- Which version of Boost was used?
- Can any later version of Boost be used?
- What would it take to upgrade Allegro to 5.0 or higher? (Or at least, a version that allows modern MSVC compilers to work?)
- Which files are we allowed to modify in case upgrading is not possible?

I'm effectively stuck at this point: until I can handle Allegro in a clean manner, I cannot contribute much to this repo.

**Comment by lonegraywolf2000** [comment]
Perhaps [Porting from Allegro 4 to Allegro 5](https://wiki.allegro.cc/index.php?title=Porting_from_A4_to_A5) is possible. Still unsure about the whole MSVC/allegro header conflict though. It may be that we have to compile Allegro now.

**Comment by Gleeok** [comment]
Any version of boost. It;s only used for boost::bind I believe.

Can we try a trivial test case really quick? Do you need both inttypes.h and stdint.h or just stdint.h?

**Comment by lonegraywolf2000** [comment]
...gah, didn't catch the email quickly.

I believe MSVC 2015 provides both inttypes.h and stdint.h. At the very least, definitely inttypes.h. I don't need a custom file. What I need is the almsvc.h header file to recognize that I have the standard types.

**Comment by lonegraywolf2000** [comment]
To better explain: on Windows, almsvc.h defines a number of Allegro based defines. It eventually goes to an allegro file where `ALLEGRO_HAVE_INTTYPES_H` is checked for. If that is not defined, it eventually gets to the point where standard types are defined. Or in my case, re-defined.

MSVC 2008 did not include inttypes.h, so defining the types was necessary. MSVC 2010 and MSVC 2012 also required the types to be defined manually. MSVC 2013, I don't recall, but MSVC 2015, I don't need the types defined. The issue is (slightly opinionated) that Allegro 4.2 was made during a time when it was always presumed that MSVC would stay behind, and that code base is no longer updated.

...the issues with ancient technology. I have encountered similar issues with another repository, and I've been fighting it for far too long.

And before I forget: `boost/function` is also used from what I can tell.

**Comment by Gleeok** [comment]
Ah. Got it. What if we do something like this in the allegro header:

#if defined(_MSC_VER) && (_MSC_VER > 1700)
#define ALLEGRO_HAVE_INTTYPES_H
#include <inttypes.h>
#endif

There should be a quick fix to get it working on VS2015.

**Comment by lonegraywolf2000** [comment]
I'll give that a shot after work today. At least I now know you are allowing us to modify the allegro files.

**Comment by lonegraywolf2000** [comment]
Too many line ending commits are throwing off my rebasing, but as far as current progress goes...I was able to edit enough files (and adjust an include or two) to allow for compiling. Unfortunately, linking is an issue. _ITERATOR_DEBUG_LEVEL is set to 0 and needs to be 2 (may have that reversed): it's related to the angelscript items.

Once I reset my personal fork, I will try to get a branch set up with hard coded project 2015 progress.

**Comment by Gleeok** [comment]
Great! :)

Can you have it use the angelscript library directly inlined in ZC? (This way there will be no headaches with version differences and bugfixes--I don't actually want to support other angelscript versions for this reason) The file to add to the build process is "angelscript_unity.cpp". 

if you still have problems you can edit the config.h file I put up for those reasons.

**Comment by lonegraywolf2000** [comment]
See #12: I actually went ahead and made a standalone branch in case cmake doesn't pan out, and...well, I'm having inconsistencies with linking AngelScript. In release mode, that portion seems to link fine, but debug mode...does not.

**Comment by Gleeok** [comment]
I see about _ITERATOR_DEBUG_LEVEL;

VC++ is always so finicky about these things.

**Comment by Gleeok** [comment]
Easy enough. Feel free to edit config.h to define those to sensible defaults. (In 2008 they all are shit so I disable them)

**Comment by lonegraywolf2000** [comment]
Last issues are linker issues: consistent across both debug and release. At this point, taking the conversation to #12 may be better.

**Comment by evouga** [comment]
Closing this for now. The Cmake file works with MSVC 2016 on my end and the stdint issues are resolved. As for Allegro 5, that is a more involved conversation. I'd prefer first factoring out the backend code into a wrapper and then trying to plug in different backends like Allegro, SDL, etc. Let's discuss on the forums.
