### ISSUE TITLE
2.50.x: Parser Is Losing InitD values when referencing by Identifier.

### ISSUE THREAD

**Issue by ZoriaRPG** [ZQuestClassic/ZQuestClassic#111]
Using the parser files dated 10th January, 2017

In ffc scripts, the values of the InitD inputs are not forwarded as local variables.

Example:

`	ffc script foo `
`	{`
`	     void run(int var_a, int var_ b, int var_c) `
`	    	{ `
`		        	int d = var_a;  `
`	        		int e = var_b; `
`	        		int f = var_c; `
`	`
`	        		int d1 = this->initD[0]; `
`	        		int e1 = this->initD[1]; `
`	        		int f1 = this->initD[2]; `
`	    	} `
`	} `

When referencing one of the variables that is used as a line param for run(), **by its Identifier**, the variable will always be a value of 0. Thus, variables d, e, and f will all be '0, whilst d1, d2, and d3 will all have the proper InitD values. I suspect it is related to the change that destroys variables when their scope exits, and I need to verify that this is not in master as well.

This likely also affects item scripts.

**Comment by evouga** [comment]
This is resolved now?

**Comment by ZoriaRPG** [comment]
Aye, it seems to be good. You can close this ticket.
