### ISSUE TITLE
JWin Dialogue File Listers Scroll Too Fast

### ISSUE THREAD

**Issue by ZoriaRPG** [ZQuestClassic/ZQuestClassic#113]
The scrolling on dialogue/file listers, when clicking on the up/down arrow buttons is far too fast on modern systems. It scrolls so fast that the entire list zips past, and there are legitimately areas in the list that you cannot reach without using arrow keys.

**Comment by evouga** [comment]
Is this a 2.50.x issue or a master issue? 
What dialog specifically is posing a problem?

I just tried File->Open in Zquest and clicking on the arrows seems to scroll at a reasonable speed...

**Comment by ZoriaRPG** [comment]
It's in both. Try the listers in ZQuest, for items, sprites, enemies, and so forth.

**Comment by evouga** [comment]
I still cannot reproduce this issue on branch 2.50.x, 800x600 windowed "big" mode, Quest->Items. Clicking on the square arrow buttons scrolls the list at a reasonable pace.

I will need *specific* steps to reproduce, including graphics settings (if the issue only appears in some other mode than 800x600 "big" windowed.)

**Comment by ZoriaRPG** [comment]
I'm not sure what was causing this, but it seems to be fixed??? I noticed on a few instances, that with multiple ZQ threads open, that some event timing loses its mind, but I have not been able to nail down the root cause.  One thing that I have noticed, at random, is that the flames logo will play very quickly, rather than at the standard framerate.

**Comment by ZoriaRPG** [comment]
I narrowed this down. and it is yet-another race condition, when more than one allegro process is open.
