### ISSUE TITLE
2.50.x: ag.cfg is being Corrupted when ZQuest Closes

### ISSUE THREAD

**Issue by ZoriaRPG** [ZQuestClassic/ZQuestClassic#115]
When ZQuest **exits**, ag.cfg is being corrupted with binary code. 

Opening the file after this occurs, it is a mangled mess, and after this happens, ZQ and ZC will not display properly. Is this also some attempt to write through the packfile encryption, like the MIDI issue?

This happens during the ZQuest close action. 

ag.cfg before and after:
http://timelord.insomnia247.nl/zc/zc_dev/ag_cfg_issue

**Comment by ZoriaRPG** [comment]
I'm not seeing the cause of this one. I looked at config.c, zquest.cpp, and some other stuff, but nothing seems to use the password stuff.  I feel as though there should be an instance of write_config() that is causing this, but I do not see where.

**Comment by gwx** [comment]
I believe I remember evouga fixing this in master by setting the password to null before saving ag.cfg, even though I couldn't find anything to do with passwords either.

**Comment by evouga** [comment]
Grayswandir is correct. Allegro changed the behavior of the global packfile password and it seems one of the fixes surrounding this change didn't get backported to 2.50.x. I am traveling today but will fix it in the next few days (if it's still unresolved)

**Comment by evouga** [comment]
Should be fixed now.
