### ISSUE TITLE
2.50.x Branch Corrupting <= 2.50.2 Quests when Recompiling Scripts. 

### ISSUE THREAD

**Issue by ZoriaRPG** [ZQuestClassic/ZQuestClassic#122]
From here:
https://www.purezc.net/forums/index.php?showtopic=72661&page=8#entry1026835

the <tl;dr> is that if you take a scripted quest from 2.50.2 (or earlier), recompile the scripts and reassign them, that when you open the quest in 2.53.0 (branch 2.50.x), either the quest data is corrupted, or there is a ZQuest memory leak that corrupts FF Data in all quests that you try to open in ZQuest **from that point onward.** 

The latter is what I experienced. When **I** recompiled, I could save, and immediately thereafter, if I try to load a quest file, or create a new quest, ZQ crashes at _Loading FF Data_.

Lut claims that he is experiencing ZQ crashing when it tries to _save_, or that the quests that he saves have corrupted data. I cannot reproduce that specific _symptom._ 

Instead, I can create a situation where ZQuest crashes whenever it tries to load FF data from the quest file after recompiling. I suspect some kind of memory leak here, corrupting the FFC data in the quest file, but I have not been able to narrow it down, and frankly, I'm stumped. 

The issue with the this (InitD) being offset, is fixed. (I remember patching that for Beta 2 or 3 with the missing push.) Thus, you can ignore that part of his post. ( He verified that Beta 4 does not have this issue. )

It might be something weird with slot assignment changes? I did not do any of the parser tinkering here, so I (1) do not recall what has changed, and (2) I am not steeped enough int he aspect of storing the bytecode and the ffc data to know what to look for; but it seems to be something bad with where ZQ is writing it. Was there some modification tot he filepack (that I did not make) that would account for this?

All of my filepack changes are in _master_, not _2.50.x_.

**Comment by evouga** [comment]
Sounds serious. To be clear, the steps to reproduce are:

1. Compile a ZScript in 2.50.2 and save the quest there;
2. Open the quest in 2.50.x and recompile the script (in 2.50.x, not 2.50.2?);
3. Assign the script to the same slots (i.e. do nothing)

and then corruption occurs? Do you have a test .qst from 2.50.2 that shows this behavior?

**Comment by ZoriaRPG** [comment]
Lut provided a very detailed report with five test files to demonstrate what he encountered in this post:
https://www.purezc.net/forums/index.php?showtopic=72661&page=7#entry1026702

Scroll down to _Compile and Compatibility Issues:_, near the bottom of that post to snag them.

I have a few test quests here, too:

http://timelord.insomnia247.nl/zc/zc_dev/2.53_Win_Beta_5.zip
I built this to test the fix on QRs that you merged earlier today, so it is current to the repo. (I did not post this on Pure, or anywhere else, but I did send the link to Lut so that he could continue testing things.).

**To confirm, the steps are:**

- Generate a quest in 2.50.2, or open an existing 2.50.x quest saved in <= 2.50.2.
- Compile some scripts in 2.50.2. I tested this with ffc scripts.
- Assign them to slots.
- Save.
- Open the quest in ZQuest from /branch 2.50.x/, i.e. 2.53.0b5 as of this post .
- Open the script editor and recompile. For Lut, this is where ZQuest crashes, some of the time.
- Save. For Lut, this is where ZQuest saves a corrupted quest, if it did not crash when compiling.
- Try opening a quest, or making a new quest.
- **At this point (for me), ZQuest crashes at Reading FF Data**

For Lut, it seems to crash _during saving_ most of the time, or it simply corrupts mapdata or combodata/tiles. 

Lut's issue seems entirely different to what I am seeing, but it is clearly something with a similar root.  He posted test quest files and a very detailed explanation on it in the thread on Pure. 

Another difference in what I have documented, is that if I let ZQuest crash, and I load the quest, it loads fine. The crash occurs after recompiling any quest made in an earlier than 2.53.0 build on my end. 

I did not set up the ffcs on any screens, as I encountered this problem without doing that, but perhaps if I had done this, then my map/combo/tile data would have been likewise corrupted. I have not tested this with master yet, either. That is an entirely different can of worms, as the parser is in such a state of flux.

None of this seems to be affecting the Bytecode/ASM side of things in quests, when you run them in Zelda.exe ... that part seems to work with no issues.

**Comment by evouga** [comment]
Fixed. The problem is actually 2.50.2, which for some reason corrupted some of the script bindings in older quests so that the .qst thinks there are a bunch of extra global script slots containing bogus scripts. I'd put a fix in master to check and ignore the corruption but forgot to backport the fix the 2.50.x.
