### ISSUE TITLE
ROMView Flat out Crashes

### ISSUE THREAD

**Issue by ZoriaRPG** [ZQuestClassic/ZQuestClassic#127]
Whatever may have changed, either in the ROMview code, or in our libs, since June, ROMView.exe flat out crashes now. The filesize of ROMView also dropped from 899K to 851K in the process.

**Comment by Gleeok** [comment]
No idea. If no one plans on adding new romview features think we should just move it to tools and allow people to download it as a separate file.

We've kind of stopped working on it for the last 10 years or so anyway.

**Comment by ZoriaRPG** [comment]
It was working a few builds ago. I used that version in the beta release, as it, well, runs and seems to work.

**Comment by evouga** [comment]
I'll look into it.

**Comment by evouga** [comment]
Romview runs fine for me (in master at least). What do you mean by a "crash"? Does it simply fail to start? Open up for a second and then crash with an access violation? Can you get a stack trace?

**Comment by ZoriaRPG** [comment]
It;s the 2.50.x version that fails to run.
