### ISSUE TITLE
Parser / ZQuest Compilation Failures of the Week

### ISSUE THREAD

**Issue by ZoriaRPG** [ZQuestClassic/ZQuestClassic#136]
Issue Number 1: >SemanticAnalyzer.cpp

You can't use **stdint.h**. If you must use its definitions, you need to write them inside one of the ZScript headers, and write them in a CPP08 compliant manner--as that file _has no analogue for MSVC9_. I have tried to use stuff that needed it before, and it pretty much always just spews a never-ending chain of errors.

 Next:

```
5>.\src\parser\ScriptParser.cpp(375) : error C2065: 'set' : undeclared identifier
5>.\src\parser\ScriptParser.cpp(375) : error C2062: type 'int' unexpected
5>.\src\parser\ScriptParser.cpp(379) : error C2065: 'usedLabels' : undeclared identifier
5>.\src\parser\ScriptParser.cpp(382) : error C2065: 'set' : undeclared identifier
5>.\src\parser\ScriptParser.cpp(382) : error C2062: type 'int' unexpected
5>.\src\parser\ScriptParser.cpp(385) : error C2065: 'unprocessedLabels' : undeclared identifier
5>.\src\parser\ScriptParser.cpp(385) : error C2228: left of '.empty' must have class/struct/union
5>        type is ''unknown-type''
5>.\src\parser\ScriptParser.cpp(385) : fatal error C1903: unable to recover from previous error(s); stopping compilation```


AND

```5>c:\users\dell\desktop\zc_2.54\___master\src\parser\library.cpp(12) : error C4716: 'ZScript::Libraries::get' : must return a value```

**Comment by evouga** [comment]
There are Allegro headers that properly define the int32_t etc. types in a cross-platform way. I don't remember the right headers to #include offhand but they definitely exist.

**Comment by gwx** [comment]
Alright, I included "zc_alleg.h" and that seemed to work. Seems kinda overkill for just a few uint32_ts though - still not sure why those were necessary in the first place.

Others fixed as well.
