### ISSUE TITLE
(ALL) Dependency Compiling Issues - vs2015, x64, osx, linux

### ISSUE THREAD

**Issue by Gleeok** [ZQuestClassic/ZQuestClassic#16]
This is currently the biggest issue at the moment: Dependency crap.

There's three related problems: 64-bit builds in general, osx/linux, vs2015 (or any other compiler that just fucking breaks stuff randomly).

I'm contemplating creating a new repository called "Zelda Classic Dependencies" as putting all the binaries for every conceivable platform configuration is just silly, as you say. This can house the complete source (and projects--as users can freely contribute new platforms as needed) and heck, even binaries for common platforms; sure, why not just cherry-pick a single folder with pre-built stuff if it exists? This is great for new people.

On the maintenance side of things in the main code base we actually don't have to micro-manage project files; by utilizing the unity-esque build_modules approach, trivial additions or deletions of cpp files will not break compilation of anything. As long as one person keeps up to date with changes then all projects stay up-to-date.

Thoughts; Ideas; Monsters?

**Comment by ghost** [comment]
In my experience it's the combination of Allegro and Windows that breaks things. They just cannot seem to get along. Example given, although NOGDI is already defined, for some reason Codeblocks wants me to define it myself.

**Comment by lonegraywolf2000** [comment]
The (main) issue with VS2015 is that Allegro 4 was written at a time when Microsoft did not care about standards. Allegro 5 is now the maintained one, with Allegro 4 only being updated, if at all, for emergencies.

I still say we should upgrade to Allegro 5, but I guess that's just wishful thinking.

As far as unity builds...I'll admit I'm still not fully convinced of them. For cmake, it shouldn't matter too much.

**Comment by zoharion** [comment]
I'm almost done compiling for an arm computer (Raspberry pi 2), but  i need libzcsound.so, wich isn't avaible for arm machines. Could you guys release the source of libzcsound so i can finish compile, please?

**Comment by Gleeok** [comment]
libzcsound isn't actually needed anymore. It's just zcsound.cpp and zcsoundd.cpp compiled and linked with the other sound libs. You can compile those two files directly into zc if you wish.

**Comment by ghost** [comment]
I disagree, no upgrade. Replace it entirely. Allegro has been around since the early 90s. Sure the library rewrite is decent. But to be honest. I hate the thing and using OpenGL directly would be a much more feasible option.

**Comment by dxgldotorg** [comment]
Are you saying that you might be able to compile ZC as 64-bit?

Will it still be using Allegro 4.x, and will it still be using DirectDraw?  If so, maybe I should start trying to compile DXGL as 64-bit?

**Comment by Gleeok** [comment]
Hasn't happened yet and it's not a huge priority or anything.

**Comment by dxgldotorg** [comment]
And I haven't tried to build DXGL in 64-bit mode either.  Probably will blow up good on the first 10 tries or so.

As for it not being a huge priority to compile ZC in 64-bit I don't see any advantage, as I don't see how a ZC game could eat up that much RAM.

**Comment by Gleeok** [comment]
Yep. I'm sure ZC would blow up as well. :P  Someone was trying to get a linux64 to compile, but I don't know anything about that.

I doubt there's any chance for a 64-bit release anytime soon though.  I believe some windows 8 users are using DXGL to run fullscreen; I assume the same for windows 10 as compatability gets worse with every new windows OS.

**Comment by dxgldotorg** [comment]
By the way, I thought Windows 10 DirectDraw was better than 8.x; they fixed the nasty framerate bug late in the beta.
