### ISSUE TITLE
Please write down how to compile on Ubuntu 17.10

### ISSUE THREAD

**Issue by xcom169** [ZQuestClassic/ZQuestClassic#188]
Please write down how to compile on Ubuntu 17.10

-Which packages needed
-Steps, commands
-Etc.

Thanks

**Comment by ZoriaRPG** [comment]
@gwx You may want to address this. I'm using Ubuntu 12.04 32-bit, and that information won't be as helpful.

@xcom169 
You need a 32-bit version of gcc, and you need to install cmake, flex, and bison.

sudo apt-get install flex
sudo apt-get install bison
sudo apt-get install cmake
sudo apt-get install libc6-dev:i386 gcc:i386
sudo apt-get update
Once you generate the build files with cmake, use the 32b make flag:
gcc "makefile" -m32 

Here are the -m flags for gcc:
https://gcc.gnu.org/onlinedocs/gcc-4.5.3/gcc/i386-and-x86_002d64-Options.html

An alternative is to install these gcc files, but IDK if they will cause issues with compiling 64b C code in the future for you:
sudo apt-get lib32gcc-4.8-dev
sudo apt-get install gcc-6-multilib
