### ISSUE TITLE
Game breaking glitches

### ISSUE THREAD

**Issue by zoharion** [ZQuestClassic/ZQuestClassic#19]
I've managed to compile Zelda Classic for arm and x86-64, however it cannot load quest files because it says "Invalid Quest FIle" and sometimes "Invalid Header String". Also, after the zelda intro everything is black, although i can still press esc and quit. It seems that the program needs some data files, fonts.dat qst.dat sfx.dat zelda.dat and zquest.dat, and by looking in an hex editor it seems that all these files have machine code inside then, so i assume that these files depend on architecture, am i right? If so, can i build these files somehow? Do these files even relate to my problem?

**Comment by Gleeok** [comment]
You can download the latest ZC release which has those files packaged with it. Make sure the file "encryptionEnabled.cpp" is compiled in this case (I just fixed an issue with this for MSVC), which should be the default but it wasn't set up right.

**Comment by zoharion** [comment]
That worked! It seems that it wasn't reading the quest files right but once i enabled encryption now the game starts, but i'm having some game breaking glitches. In flow of time when i go to fight the last boss the game crashes, this also happens on level 7 when trying to load the first screen. Also when i try to target a block with the hookshot Link goes out of the game forever and disappears. I have tested  Banana blood god as well and sometimes when i enter in some door  everything but the character turns black, am i the only one having these glitches?

**Comment by Gleeok** [comment]
Thanks for the bug report. The crashes are due to particular enemies I believe. Every new version of ZC has some random hookshot bug also...  Will look into all of these before next release.

**Comment by ghost** [comment]
@Saffith
Just how consolidated is the hookshots code now? I know you abstracted most of it into hookshot.cpp. I think only the code for the actual weapons themself are still in weapons.cpp Right?

**Comment by evouga** [comment]
Closing as stale. If hookshot bugs remain in 2.50.3, please file a new report.
