### ISSUE TITLE
bind.h

### ISSUE THREAD

**Issue by ghost** [ZQuestClassic/ZQuestClassic#21]
It's not included in the makefile Gleeok. Probably should add that.

**Comment by Gleeok** [comment]
There is none.

**Comment by ghost** [comment]
@Saffith 
Saffith please update the makefile, thanks.

**Comment by Gleeok** [comment]
I don't use the makefile but It's just a simple header file. that includes functional on compilers that have c++11 support so that users are not required to install boost.

Did I break something?

**Comment by ghost** [comment]
If that's the case I can add it myself sounds easy enough.
