### ISSUE TITLE
Mac version ZC opens to black screen

### ISSUE THREAD

**Issue by Pysis868** [ZQuestClassic/ZQuestClassic#223]
After continuing through the Armageddon Games splash screen and TLoZ re-made title screen, the screen cuts to black, with some small differently-colored squares in the corners.
![image](https://user-images.githubusercontent.com/1408565/47260281-85c84180-d486-11e8-8e6c-720071c47b1b.png)
Those squares were present the entire time since initial application load.
They do not seem to appear in this window screenshot, but are there, and may not be recorded by the screenshot function.  The bottom left contains  white square, and the bottom right contains a transparent square, showing whatever is under the window.

The game is not frozen, as I can cause file selection screen noises to occur.

ZQuest Editor.app opens the new quest simply presenting a `Decrypting...error` message.

I have noticed that it will ask to create a new save file every time when opened this way.

https://www.purezc.net/forums/index.php?showtopic=72905
Tried suggestion(s) from here to move the apps, and even made a brand new folder to move and run them from there as well, attempting to avoid some "Gatekeeper Path Randomization, also known as app translocation" issue, but still have the same result.  The forum thread does not seem to be that old, so it should be similar enough to my current Mac OS.

This was also all after the initial [Gatekeeper] prompts I had to force past using the typical context menu Ctrl+'Open' bypass method.

While looking for system log entries, I realized I could run the executable directly from inside the application package: `'.../Zelda Classic.app/Contents/MacOS/Zelda Classic'`

I see these log entries:
```
2018-10-20 16:41:21.218 Zelda Classic[33434:4656127] Warning once: This application, or a library it uses, is using NSQuickDrawView, which has been deprecated. Apps should cease use of QuickDraw and move to Quartz.
Oct 20 16:41:21  Zelda Classic[33434] <Error>: The function ‘SLSFlushWindow’ is obsolete and will be removed in an upcoming update. Unfortunately, this application, or a library it uses, is using this obsolete function, and is thereby contributing to an overall degradation of system performance. Please use `SLSFlushWindowContentRegion' instead.
```

This time it works, where I see the file selection screen as the third one, and no white corner boxes.  Also, `zc.sav` is successfully created using only this method and then closing the application.

```
~ tree -F '.../Zelda Classic.app/' | sed 's|\\\ | |g'
.../Zelda Classic.app/
└── Contents/
    ├── Frameworks/
    │   ├── Allegro.framework/
    │   │   ├── Allegro -> Versions/Current/Allegro*
    │   │   ├── Headers -> Versions/Current/Headers/
    │   │   ├── Resources -> Versions/Current/Resources/
    │   │   └── Versions/
    │   │       ├── 4.2.2/
    │   │       │   ├── Allegro*
    │   │       │   ├── Headers/
    │   │       │   │   ├── aintosx.h*
    │   │       │   │   ├── aintunix.h*
    │   │       │   │   ├── allegro.h*
    │   │       │   │   ├── alosx.h*
    │   │       │   │   ├── alosxcfg.h*
    │   │       │   │   ├── alplatf.h*
    │   │       │   │   ├── astdint.h*
    │   │       │   │   └── osxalleg.h*
    │   │       │   └── Resources/
    │   │       │       ├── Embeddable
    │   │       │       └── Info.plist
    │   │       └── Current -> 4.2.2/
    │   └── libzcsound.dylib*
    ├── Info.plist
    ├── MacOS/
    │   └── Zelda Classic*
    ├── PkgInfo
    └── Resources/
        ├── 1st.qst
        ├── 2nd.qst
        ├── 3rd.qst
        ├── 4th.qst
        ├── 5th.qst
        ├── 5thmusic.nsf
        ├── ag.cfg
        ├── allegro.log
        ├── fonts.dat
        ├── qst.dat
        ├── sfx.dat
        ├── zc.icn
        ├── zc.sav
        ├── zc_icon.icns
        ├── zelda.dat
        └── zelda.nsf*

12 directories, 32 files
```

macOS Sierra 10.12.6
MacOS X Windowed Quartz
640x480 8-bit
Tried with both ZC 2.50.2 and 2.50.3-rc1 from the dmg archives on the main site downloads page.

**Comment by ZoriaRPG** [comment]
'Pysis868 Unfortunately, Apple have been deprecating a lot of stuff that has, historically, been a fundamental part of the OS. The next version of OSX will no longer support 32b apps **at all**, so, until we have ZC ported to OpenGL *and* 64b, OSX support for OS versions > 10.11, is suspended. 

At present we have no active OSX developer.

**Comment by EmilyV99** [comment]
As zoria mentioned, OSX support is dead. We are currently struggling to restore linux support due to having very few active devs, all of whom are windows users. Even if we wanted to get OSX builds working again, it simply *can't* work on modern OSX due to Apple deciding that they hate developers.

Frankly, apple is a piece of crap, and don't care about anything but money. Not a single care for its' users or community. And there isn't much we can do when a company just decides that all 32-bit apps are dead on its' platform. 64-bit version of ZC is still a ways away from being feasible.
