### ISSUE TITLE
Floaters and Wizzrobes ignore dungeon borders

### ISSUE THREAD

**Issue by ghost** [ZQuestClassic/ZQuestClassic#25]
```
// Returns true if enemy is floating and blocked by a combo type or flag.
bool flyerblocked(int dx, int dy, int special)
{
    return ((special==spw_floater)&&
            ((COMBOTYPE(dx,dy)==cNOFLYZONE)||
             (combo_class_buf[COMBOTYPE(dx,dy)].block_enemies&4)||
             (MAPFLAG(dx,dy)==mfNOENEMY)||
             (MAPCOMBOFLAG(dx,dy)==mfNOENEMY)));
}

bool m_walkflag(int dx,int dy,int special, int x, int y)
{
    int yg = (special==spw_floater)?8:0;
    int nb = get_bit(quest_rules, qr_NOBORDER) ? 16 : 0;

    if(dx<16-nb || dy<zc_max(16-yg-nb,0) || dx>=240+nb || dy>=160+nb)
        return true;

    if(isdungeon() || special==spw_wizzrobe)
    {
        if((x>=32 && dy<32-yg) || (y>-1000 && y<=144 && dy>=144))
            return true;

        if((x>=32 && dx<32) || (x>-1000 && x<224 && dx>=224))
            if(special!=spw_door)                                 // walk in door way
                return true;
    }

    switch(special)
    {
    case spw_clipbottomright:
        if(dy>=128 || dx>=208) return true;

    case spw_clipright:
        break; //if(x>=208) return true; break;

    case spw_wizzrobe:
    case spw_floater:
        return false;
    }

    dx&=(special==spw_halfstep)?(~7):(~15);
    dy&=(special==spw_halfstep || tmpscr->flags7&fSIDEVIEW)?(~7):(~15);

    if(special==spw_water)
        return (water_walkflag(dx,dy+8,1) || water_walkflag(dx+8,dy+8,1));

    return _walkflag(dx,dy+8,1) || _walkflag(dx+8,dy+8,1) ||
           groundblocked(dx,dy+8) || groundblocked(dx+8,dy+8);
}
```

If they're not No Flying Enemy combos that is to say. Also effects Teleporting wizzrobes in some cases.
I believe this is the cause.

if((x>=32 && dy<32-yg) || (y>-1000 && y<=144 && dy>=144))

**Comment by Saffith** [comment]
As far as I can tell, that only happens on non-dungeon screens, which I wouldn't consider a bug. Teleporting wizzrobes are supposed to ignore borders; they can appear in doors in the NES game.

**Comment by ZoriaRPG** [comment]
Not a bug, but I'd accept this an an improvement, if it's controlled by enemy editor attributes.

**Comment by ghost** [comment]
No Saffith, it effects all screens. And no teleporting wizzrobes are not to ignore borders. They could appear in doorways, but not on top of walls. And you guys wonder why I'm gone.

**Comment by ghost** [comment]
fun fact if you set any fliers head homing factor to 255 it will follow you into the door.

**Comment by evouga** [comment]
Closing as stale. If Wizzrobe behavior remains buggy in 2.50.3, please file a new report. Note that if we change this we probably need a quest rule, and an investigation into when, if ever, the Wizzrobe border behavior was working in past public releases.
