### ISSUE TITLE
Zelda Classic seem very slow when it launch with Steam on Debian

### ISSUE THREAD

**Issue by kadogo** [ZQuestClassic/ZQuestClassic#27]
Hello, I have a weird issue.
When I launch ZC with zelda-l or zlauncher it work without issue.
But when I run it with Steam as non-steam game, I see the Armageddon logo very slowly.

I do ctrl + alt + F1, the sound seem good so I go back with ctrl + alt + F7 but the game is freeze.
(Seem if I try to kill it with pkill -9 it hold the the loge screen in a freeze).

I launch the game in Steam do make the configuration of the Steam controller.
I tried to do the configuration in ZC directly but it seem not recognize all the buttons.

If you need more informations, let me now.
Cheers.

**Comment by kadogo** [comment]
I noticed something.
I have the same problem if I run the game and have steam running too.
(Logo and audio are slow)

I'm the only one to have that ?

**Comment by evouga** [comment]
Are you running fullscreen, or windowed?

**Comment by kadogo** [comment]
The problem is fullscreen and windowed.

**Comment by msypkenssmit** [comment]
I have the same issue on Debian. I used to be able to run it both windowed and fullscreen. Now I can only do it at 320x240. At higher resolutions it behaves as described above by kadogo. Xorg is using 100% cpu. When I switch to a console outside of X then I hear the music catching up again and regaining normal speeds. I don't know what changed except some apt-get upgrades. I have Intel integrated graphics. Other games all work fine.

**Comment by kadogo** [comment]
I just saw the PR, it's possible to have a release somewhere so I can test it ?
I tried to build but  think I miss something.

**Comment by ZoriaRPG** [comment]
@msypkenssmit 
@kadogo

I need more information about your systems.

Please provide the following:

Full OS version, architecture (i386, x64, etc), kernel version, Xorg version, and GUI shell type (Gnome, KDE, Unity, other).

Please detail your exact CPU specs, video card specs, video chipset, and so forth.

There are a number of Allegro video configuration options, and I am going to be putting them into the ZCL launcher--I have this done on Windows, but not yet on the Linux versison of ZCL. That, and 2.53 for Linux, should be forthcoming.

I **_also need to know_** if you are using the Allegro library that we provide, or if you are using one that you pulled from a package manager. They are **not** the same.

If you build Allegro, you need to use this _specific_ repo and branch:
https://github.com/ArmageddonGames/allegro5/tree/4.4-ZCFixes

If you are compiling ZC, please provide your compiler details. (ZC can only be compiled with a 32b compiler.)

If you are running one of the old Linux binary packages, then please specify the version.

The current supported source base is 2.53.0, beta; and the next target for Linux is from this branch:
https://github.com/ArmageddonGames/ZeldaClassic/tree/2.50.x

The ZCL repo for 2.53, is here:
https://github.com/ZoriaRPG/ZCLaunch

If you wish to compile ZCL, you will need the Lazarus IDE (32-bit ONLY). I will be adding the config settings for the Linux Allegro video drivers in the next version.

---

My Linux dev environment is as follows:
Ubuntu 11.10, with Unity (32-bit, i86), Kernel 3.0
Intel Core i7-2620M @ 2.70GHz/2.70GHz
Intel QM67 chipset
Intel HD Graphics 3000
NVIDIA NVS 4200M Discrete Graphics
12GB RAM

**Comment by kadogo** [comment]
@ZoriaRPG 
I will try it in the evening or next week.
It's ok to make the test on the last beta release from github ?

**Comment by msypkenssmit** [comment]
I still experience the same issue. I have just tried with both v2.50.2 and v2.50.3 [RC1]. I'm using the precompiled packages from ZeldaClassic.com.

My system is:
Debian stable 9.2 (Stretch), with KDE Plasma (I also have the problem under other, more lightweight desktops), Kernel: 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux
I have installed the required i386 libraries from Debian packages (multiarch).
Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
VGA compatible controller: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller (rev 06)
8 GB RAM
[Xorg.0.log](https://github.com/ArmageddonGames/ZeldaClassic/files/1504166/Xorg.0.log)

I do not have allegro installed on my system. I have considered building it myself in the past, but found it too difficult, requiring installation of too many extra packages, to want to go through with that.

Let me know if you need more or other information than this.

**Comment by ZoriaRPG** [comment]
@kadogo
Pleade use the current state of the 2.50.x branch, and the Allegro branch that I posted earlier.

@msypkenssmit 
That build is years out of date now, using Allegro 4.2.

 I will see what I can do, to get a Linux build of 2.53.0 out soon.

I see that you have a single-core i5. For whatever reason, the allegro thread loves eating all of the cycles on a given core.
.
I'm not sure why the allegro process was eating a full CPU core. It might be better now, but again, it may not be better.
