### ISSUE TITLE
[ZC 2.55a17] Regressions in custom quest "Link and Zelda: Panoply of Calatia"

### ISSUE THREAD

**Issue by dxgldotorg** [ZQuestClassic/ZQuestClassic#331]
When starting the custom quest "Link & Zelda: Panoply of Calatia" version 1.66 a sword sprite blinks momentarily before the title screen appears, then is persistently visible during the title sequence, as can be seen between the title and the water:
![image](https://user-images.githubusercontent.com/7480507/56154697-28b9ce00-5f87-11e9-9c63-bcf4278aec56.png)

It continues to be visible in the settings menu:
![image](https://user-images.githubusercontent.com/7480507/56154744-49822380-5f87-11e9-9a4f-f98e316a51cb.png)

Finally, in the intro cutscene it is visible inside the Triforce when there is no dialog visible:
![image](https://user-images.githubusercontent.com/7480507/56154775-5dc62080-5f87-11e9-85f9-7e025c2200f0.png)

As noted in the title the player is Zelda Classic 2.55 Alpha 17, and the custom quest version is 1.66 from the PureZC site.

**Comment by dxgldotorg** [comment]
Another issue found in the same quest:
In the following room:
![image](https://user-images.githubusercontent.com/7480507/56163655-e56a5a00-5f9c-11e9-880d-8fb129a46749.png)

I cannot go underneath the bridge to the other side of the room.  In 2.53r2 it is fine.

**Comment by ZoriaRPG** [comment]
@dxgldotorg We're up to Alpha 21. Does this still happen there?

It's a pretty heavily scripted quest, and the scripts are rather hard to read/debug. 

The sword sprite is probably some kind of generic weapon that Mitsukara used that is now not using a blank tile. I can't explain the second issue at all, as I have no clue what is special about that room.

One recent build had a bug where Link was always treated as fulltile collision, so, perhaps that was the culprit? Please try it in Alpha 21 and let me know if it persists. You can download it at https://zeldaclassic.com/downloads

**Comment by ZoriaRPG** [comment]
@dxgldotorg I tried the quest in Alpha 21. The sword sprite issue did not occur for me, and I asked Mitsukara about that room:

That walk path is half-solid, so, I suspect that Alpha 17 was the build where full-tile-collision was unintentionally enabled by default. Please give the latest build a try, as it should be safe now.

**Comment by dxgldotorg** [comment]
Looks like you can close this issue now, as both bugs appear fixed on my end.
Never mind, I closed it myself.
