### ISSUE TITLE
Allegro 4 rotate_sprite_trans Not Available?

### ISSUE THREAD

**Issue by ZoriaRPG** [ZQuestClassic/ZQuestClassic#34]
Any attempt to call rotate_sprite_trans(), which is an allegro 4 drawing function, returns an error. 

It seems to be missing from our ag4 implementation?! Please verify.

**Comment by evouga** [comment]
What do you mean by "returns an error"? The function doesn't have a return value.

Do you mean it doesn't compile? Or crashes at runtime?

**Comment by Gleeok** [comment]
I believe rotate_sprite_trans() is an allegro 4.4 only function. If you are upgrading to 4.4 solely for the newer drawing routines (there's about 8 new ones IIRC) it might be easier to simply copy over those functions instead.

**Comment by evouga** [comment]
Allegro 4.4 is merged in now.
