### ISSUE TITLE
add images for menu/desktop launchers

### ISSUE THREAD

**Issue by ghost** [ZQuestClassic/ZQuestClassic#357]
It would be nice to include some images for use in desktop/menu  launchers. For the editor and for the game it self.

**Comment by ZoriaRPG** [comment]
Example, please? Other than icons, what do you mean here?

**Comment by ghost** [comment]
Yes, add a default image to be used in a launcher. That's it.

**Comment by EmilyV99** [comment]
ZC, ZQ, and Zlauncher all have (and always have had) icons.... so, uh, what are you asking for here?

**Comment by ghost** [comment]
i'm on linux, i don't know what happens on the windows side.
You need an actual image file in the folder, preferably a png, not just embedded in the executable. This way you can define a pretty menu launcher with official art of the project. Usually, they are several of different sizes, for menus, on the desktop, high density screens etc.... For example with firefox, they are icons from 16x16 to 128x128 pixels.

**Comment by EmilyV99** [comment]
>You need an actual image file in the folder, preferably a png

The repo should have '.ico, .xpm, .rc, .icns' for every program's icon. If you'd like to pull request adding a png, feel free.
