### ISSUE TITLE
zelda.exe crash when pushing win key to switch to desktop.

### ISSUE THREAD

**Issue by regneq** [ZQuestClassic/ZQuestClassic#39]
I just compiled the updated source on VS2015 which now can be use with cmake.  I am using Windows 10 and it works great when in game.  But everytime I push the win key to switch.  Game crashed.

**Comment by evouga** [comment]
I'm aware of the problem; unfortunately it's a bug in Allegro's use of the (aging) DirectDraw library. This is currently the highest-priority issue I'm working on and hope to have a fix soon.

**Comment by evouga** [comment]
I believe this is fixed now?

**Comment by regneq** [comment]
yes,  I compiled it the other day and there was no crash.   It was also nice that I can adjust the window screen if I decided that I didn't want full screen.   Thanks for the hard work.
