### ISSUE TITLE
Error trying compiling with vs 2008

### ISSUE THREAD

**Issue by vaualbus** [ZQuestClassic/ZQuestClassic#4]
I can get the program compiled. I'm using vs2008 as the newer version give me even problem.
In the lib folder we miss alld.lib. If I download and use the allegro 4.2.2 version I get missed symbol.
__imp_pack_fopen_password() and cannot compile.
On zquest I get missing sysmbol from FFCSet::FFCSet, FFCSet:clear.

**Comment by ghost** [comment]
Are you using the fixed version or your own version. You need to use the version AGN provides.

**Comment by vaualbus** [comment]
ya but there no alld.lib in the libs folder. So I cannot use the modify
version. Where I can find the lib for the modified version?

2016-01-27 22:14 GMT+01:00 Meroune Lorelie notifications@github.com:

**Comment by Gleeok** [comment]
Should be alld_crt.lib. Though I see there is no .dll for that version. I _think_ you don't even need the debug version. (Been a while since I had to debug allegro)

Will look into the zquest problem.

**Comment by Gleeok** [comment]
VC++ builds should no longer require debug versions of allegro.
