### ISSUE TITLE
Compiling without Bison/Flex

### ISSUE THREAD

**Issue by connorjclark** [ZQuestClassic/ZQuestClassic#426]
Having trouble compiling the ZScript module w/o Bison/Flex.

The first problem was simple:

![image](https://user-images.githubusercontent.com/4071474/62277962-119ad100-b3fc-11e9-9db5-1814e08e9dab.png)

Adding a forward declaration to `NoScriptParser.cpp` fixes that: `class ScriptsData;`.

The next issue I'm not knowledgable enough to solve:

```
[  5%] Linking CXX executable zquest
CMakeFiles/zquest.dir/src/zquest.cpp.o: In function `.L5298':
zquest.cpp:(.text+0x3ed12): undefined reference to `ZScript::compile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
zquest.cpp:(.text+0x3f3fe): undefined reference to `ZScript::ScriptType::ffc'
zquest.cpp:(.text+0x3f40d): undefined reference to `ZScript::operator==(ZScript::ScriptType const&, ZScript::ScriptType const&)'
zquest.cpp:(.text+0x3f43a): undefined reference to `ZScript::ScriptType::item'
zquest.cpp:(.text+0x3f449): undefined reference to `ZScript::operator==(ZScript::ScriptType const&, ZScript::ScriptType const&)'
zquest.cpp:(.text+0x3f476): undefined reference to `ZScript::ScriptType::npc'
zquest.cpp:(.text+0x3f485): undefined reference to `ZScript::operator==(ZScript::ScriptType const&, ZScript::ScriptType const&)'
zquest.cpp:(.text+0x3f4b2): undefined reference to `ZScript::ScriptType::eweapon'
zquest.cpp:(.text+0x3f4c1): undefined reference to `ZScript::operator==(ZScript::ScriptType const&, ZScript::ScriptType const&)'
zquest.cpp:(.text+0x3f4ee): undefined reference to `ZScript::ScriptType::lweapon'
zquest.cpp:(.text+0x3f4fd): undefined reference to `ZScript::operator==(ZScript::ScriptType const&, ZScript::ScriptType const&)'
zquest.cpp:(.text+0x3f52a): undefined reference to `ZScript::ScriptType::link'
zquest.cpp:(.text+0x3f539): undefined reference to `ZScript::operator==(ZScript::ScriptType const&, ZScript::ScriptType const&)'
zquest.cpp:(.text+0x3f566): undefined reference to `ZScript::ScriptType::dmapdata'
zquest.cpp:(.text+0x3f575): undefined reference to `ZScript::operator==(ZScript::ScriptType const&, ZScript::ScriptType const&)'
zquest.cpp:(.text+0x3f5a2): undefined reference to `ZScript::ScriptType::screendata'
zquest.cpp:(.text+0x3f5b1): undefined reference to `ZScript::operator==(ZScript::ScriptType const&, ZScript::ScriptType const&)'
zquest.cpp:(.text+0x3f5de): undefined reference to `ZScript::ScriptType::itemsprite'
zquest.cpp:(.text+0x3f5ed): undefined reference to `ZScript::operator==(ZScript::ScriptType const&, ZScript::ScriptType const&)'
zquest.cpp:(.text+0x3f617): undefined reference to `ZScript::ScriptType::global'
zquest.cpp:(.text+0x3f626): undefined reference to `ZScript::operator==(ZScript::ScriptType const&, ZScript::ScriptType const&)'
collect2: error: ld returned 1 exit status
```

I'm building with an Ubuntu Docker image, and using cmake/make. Details on the Docker setup (I don't think it's relevant, but just in case...):

Dockerfile
```
FROM i386/ubuntu

RUN apt-get update && \
    apt-get -y install g++ g++-multilib cmake pkg-config libasound2-dev libx11-dev libxext-dev libxcursor-dev libxxf86vm-dev libxpm-dev && \
    rm -rf /var/lib/apt/lists/*
```
(run from build folder):
```
docker build -t zc-build . && docker run -v `pwd`/..:/zc -it zc-build /bin/bash -c "cd /zc/build && cmake .. && make"
```

Are the Makefiles meant to work for the "no zscript" path? I could just install bison/flex and really get the parser module, wondering if that's necessary or if I'm just doing something wrong here.

**Comment by ZoriaRPG** [comment]
First, what **branch** are you building, and why are you building without flex/bison? They are effectively mandatory at this point.

Are you running cmake, or trying to use some extremely outdated makefile?

Do sudo apt get flex and sudo apt get bison, or the equivalent on your distro/package manager.

The only live/active ZC branches from which you should build are `2.53`and `2.55`.

**Comment by connorjclark** [comment]
> First, what branch are you building, and why are you building without flex/bison? They are effectively mandatory at this point.

I'm using branch 2.55. I was just following the build instructions, and it seemed it should be possible to build even without flex/bison. I understand it doesn't make much sense to _want_ to  (And I don't want to, I just wanted to understand the build process). Will you consider a PR from me that tweaks the language surrounding that a bit?

> Are you running cmake, or trying to use some extremely outdated makefile?

I was using cmake - `cd /zc/build && cmake .. && make` is the pertinent part of the docker command above.

> Do sudo apt get flex and sudo apt get bison, or the equivalent on your distro/package manager.

I'll try that out with my docker setup!

I'm on a newer Mac, so I think building it natively isn't going to work (allegro 4 uses deprecated systems libraries for mac). I'm hoping Docker works enough to at least build the project, even if I won't be able to also run it on the host OS.

**Comment by ZoriaRPG** [comment]
What is the target OS for Docker? I take it that it is compiling for Linux, not Darwin?
I'll need to look it up, and see what information I can find to provide better support. There may be a host of issues with non-MSVC compilers at this point. 

Are flex and bison not available to your compiler at all? The POSIX stuff that I had under OSX 10.5.8 for running Linux/BSD POSIX software, and building it under OSX had flex. Worst case here, is that you may need to build flex and bison from src and configure them.

Let me know what the target OS is, so that I can send you to the right Allegro deps, too. 

Sadly, OSX support is effectively dead, for the present, thanks to Apple's recent boneheaded and opportunistic decisions: https://www.zeldaclassic.com/2019/10/macos-support-is-sadly-at-an-end/

I wa ted to get 2.53 and 2.55 working, using my old Mac Pro 2008 tower, but this is just a disaster, If we built it now, it'd be no more than a support nightmare.

Anyway, I'm unsure if we can properly segregate out the ZScript compiler from 2.55. In 2.50/2.53, this was possible because of less integration with the host engine, hence the option.--it's a carryover that we should remove. (I don't think that it's legal to guard out all of the code involved with preprocessor directives.)

I'll need to see how it was set up in 2.50, and look for some spot to include it, possibly in the section that builds the parser, rather than where the files are included.

**Comment by ZoriaRPG** [comment]
I took a little look at Docker, and I think you are likely to hit a solid wall as soon as you need to run the linker. Either that, or you will need to manually build every dependency and see if they work. 

I've had a hard time trying to do that on an old version of Windows with MSVC 2008 and MinGW: The deps want to be built with 2006-era C99 compilers.

Have you built allegro using Docker yet? I estimate a <10% chance that the included allegro libs will link within the Docker system.

**Comment by ZoriaRPG** [comment]
Any updates @connorjclark  ?

**Comment by connorjclark** [comment]
I was never able to build allegro (in Docker), but I did have success simply linking the already-built library file, so that worked good enough. https://github.com/connorjclark/zquest-data/blob/b51e24c3dae9c61e6c77bcd63214341d707a6674/setup.py#L39

I was only trying to build just enough to build some parts of the codebase, but I ran into too many issues and moved on from building in Docker. It was a doomed prospect :)
