### ISSUE TITLE
Screen resolution - using the native desktop resolution with integer scaling enabled

### ISSUE THREAD

**Issue by Gagert** [ZQuestClassic/ZQuestClassic#517]
I used to play custom quests in Zelda Classic regularly 10-11 years ago, and I remember how the user interface used to look like back then.

I just downloaded Zelda Classic version 2.53 from the home page of ZC, and the Zelda Classic Launcher still retains the same design as it did many years ago. I'm met with a Screen Resolution menu with a couple of fixed screen resolutions, from 320x240 to 1600x1200.

Are there any plans of modernizing this, in that making you having the ability to just use your native screen resolution (mine's 1920x1080) and having the games resolution do integer scaling automatically to make the image as big as it can be with perfect square pixels and correct aspect ratio within your native screen resolution?

Edit: For older versions of Zelda Classic, where the max resolution was 640x480, I had to use dgVoodoo2 with its ddraw wrapper to output higher resolutions.

**Comment by EmilyV99** [comment]
You can edit 'zc.cfg' with custom resolution values; 'resx = val', 'resy = val'
ZQuest, does not have resolution options at this time; so the editor is effectively fixed-size. It has integer scaling options, but simply 2x is too large to fit on most monitors, resulting in the program being unable to launch.

**Comment by ZoriaRPG** [comment]
You can use also fullscreen, safely, via the bundled DXGL software on most modern systems. You may need 2.53.1 to gain access to that feature via ZCL, but DXGL and ZCL 2.8.0, along with the required support files are safe to use with 2.50.3.

**Comment by Gagert** [comment]
Seems like I'm having issues with running Zelda Classic in 1280x960 after choosing that particular resolution in the Zelda Classic Launcher. It was however fixed by copying over the dgVoodoo2 files I had from folders of older Zelda Classic releases to Zelda Classic 2.53; dgVoodoo2 with its ddraw wrapper did the integer scaling and so on for me automatically.

**Comment by connorjclark** [comment]
Latest nightlies have much better support for screen scaling, with options to keep an integer scale / use "Linear scaling" vs "Nearest neighbor". You can find the options in the launcher.
