### ISSUE TITLE
Improving the music quality of some quests with some kind of midi wrappers

### ISSUE THREAD

**Issue by Gagert** [ZQuestClassic/ZQuestClassic#518]
For 10 or 11 years ago I played a Zelda Classic Quest named A Link to the Heavens, and my PC back then was equipped with a fairly modern Sound Blaster card (can't remember which one though).

I remember that this particular Sound Blaster card had its own way of playing midi files, making them sound way richer and fuller than they usually did. In A Link to the Heavens I remember how epic the music on the swamp section surrounding the first dungeon sounded on that Sound Blaster card, and in comparison how thin the same swamp theme sounds on a modern sound card without those settings applied.

It would be cool to have some kind of midi-equalizer/wrapper settings within Zelda Classic itself, maybe having the option to make the midi's sound more like they did on Sound Blaster cards with its way of playing midi files?

**Comment by ZoriaRPG** [comment]
MIDI likewise, is still Allegro. You can play a variety of chiptune formats in ZC if you want better music in a quest, or try soundfonts. I have no experience with the latter.

**Comment by connorjclark** [comment]
FYI, settings menu in the browser menu has some support for changing the midi instruments used https://hoten.cc/zc/play/

Otherwise, you need to install your own sound font files and ZC should just pick them up, I think.
