### ISSUE TITLE
Sprite Editor Doesn't Show Sprite Number

### ISSUE THREAD

**Issue by ywkls** [ZQuestClassic/ZQuestClassic#60]
In the menu under Quest->Graphics->Sprites->Weapons/Misc is the sprite editor. This is used a lot to make custom graphics for things like weapons and items. Also, referencing a specific sprite number is often done by scripts to set these things up.

However, the menu only shows the name and visual appearance of each sprite. This means that to find out the specific sprite number, you have to click on one of them to see that info. 

Having the sprite number displayed at all times once that menu was opened would make things easier, since you could determine which sprite numbers were already being used or shouldn't be changed more readily.

Since the enemy editor and item editor already have this option, I'm not sure why it isn't included in the sprite editor.

**Comment by evouga** [comment]
Good idea. Done.
