### ISSUE TITLE
Does not compile.

### ISSUE THREAD

**Issue by ZoriaRPG** [ZQuestClassic/ZQuestClassic#62]
Grayswandirs changes to the parser do not compile on MSVC9.

1>------ Build started: Project: ZERO_CHECK, Configuration: Release Win32 ------
1>Checking Build System
1>CMake does not need to re-run because C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/CMakeFiles/generate.stamp is up-to-date.
1>Build log was saved at "file://c:\Users\DELL\Desktop\ZC_2.54\2.54_Merge\ZERO_CHECK.dir\Release\BuildLog.htm"
1>ZERO_CHECK - 0 error(s), 0 warning(s)
2>------ Build started: Project: zcsound, Configuration: Release Win32 ------
3>------ Build started: Project: romview, Configuration: Release Win32 ------
3>Compiling...
2>Compiling...
3>UB_RomviewGUI.cpp
2>UB_SoundLibCore.cpp
2>Creating library...
2>Build log was saved at "file://c:\Users\DELL\Desktop\ZC_2.54\2.54_Merge\zcsound.dir\Release\BuildLog.htm"
2>zcsound - 0 error(s), 0 warning(s)
4>------ Build started: Project: zelda, Configuration: Release Win32 ------
5>------ Build started: Project: zquest, Configuration: Release Win32 ------
5>[FLEX][ZScriptLexer] Building scanner with flex 2.5.37
4>Compiling...
4>UB_ZeldaSubscreen.cpp
5>[BISON][ZScriptParser] Building parser with bison 2.7
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:441.66: warning: a ';' might be needed at the end of action code
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:441.66:     future versions of Bison will not add the ';'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:443.66: warning: a ';' might be needed at the end of action code
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:443.66:     future versions of Bison will not add the ';'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:447.78: warning: a ';' might be needed at the end of action code
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:447.78:     future versions of Bison will not add the ';'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:458.68: warning: a ';' might be needed at the end of action code
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:458.68:     future versions of Bison will not add the ';'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:460.68: warning: a ';' might be needed at the end of action code
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:460.68:     future versions of Bison will not add the ';'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:462.58: warning: a ';' might be needed at the end of action code
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:462.58:     future versions of Bison will not add the ';'
3>UB_RomviewCore.cpp
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:464.53: warning: a ';' might be needed at the end of action code
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:464.53:     future versions of Bison will not add the ';'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:466.59: warning: a ';' might be needed at the end of action code
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:466.59:     future versions of Bison will not add the ';'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:473.68: warning: a ';' might be needed at the end of action code
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:473.68:     future versions of Bison will not add the ';'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:475.70: warning: a ';' might be needed at the end of action code
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:475.70:     future versions of Bison will not add the ';'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:477.70: warning: a ';' might be needed at the end of action code
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:477.70:     future versions of Bison will not add the ';'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:482.66: warning: a ';' might be needed at the end of action code
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:482.66:     future versions of Bison will not add the ';'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:484.68: warning: a ';' might be needed at the end of action code
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:484.68:     future versions of Bison will not add the ';'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:489.70: warning: a ';' might be needed at the end of action code
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:489.70:     future versions of Bison will not add the ';'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:491.70: warning: a ';' might be needed at the end of action code
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:491.70:     future versions of Bison will not add the ';'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:496.62: warning: a ';' might be needed at the end of action code
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:496.62:     future versions of Bison will not add the ';'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:498.62: warning: a ';' might be needed at the end of action code
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:498.62:     future versions of Bison will not add the ';'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:500.62: warning: a ';' might be needed at the end of action code
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:500.62:     future versions of Bison will not add the ';'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:502.62: warning: a ';' might be needed at the end of action code
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:502.62:     future versions of Bison will not add the ';'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:507.62: warning: a ';' might be needed at the end of action code
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:507.62:     future versions of Bison will not add the ';'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:509.62: warning: a ';' might be needed at the end of action code
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:509.62:     future versions of Bison will not add the ';'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:514.71: warning: a ';' might be needed at the end of action code
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:514.71:     future versions of Bison will not add the ';'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:519.72: warning: a ';' might be needed at the end of action code
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:519.72:     future versions of Bison will not add the ';'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:524.70: warning: a ';' might be needed at the end of action code
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:524.70:     future versions of Bison will not add the ';'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:529.66: warning: a ';' might be needed at the end of action code
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:529.66:     future versions of Bison will not add the ';'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:534.64: warning: a ';' might be needed at the end of action code
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:534.64:     future versions of Bison will not add the ';'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:539.72: warning: a ';' might be needed at the end of action code
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:539.72:     future versions of Bison will not add the ';'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:541.80: warning: a ';' might be needed at the end of action code
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:541.80:     future versions of Bison will not add the ';'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:543.82: warning: a ';' might be needed at the end of action code
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:543.82:     future versions of Bison will not add the ';'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:545.82: warning: a ';' might be needed at the end of action code
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:545.82:     future versions of Bison will not add the ';'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:547.84: warning: a ';' might be needed at the end of action code
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:547.84:     future versions of Bison will not add the ';'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:549.84: warning: a ';' might be needed at the end of action code
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:549.84:     future versions of Bison will not add the ';'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:551.84: warning: a ';' might be needed at the end of action code
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:551.84:     future versions of Bison will not add the ';'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:553.84: warning: a ';' might be needed at the end of action code
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:553.84:     future versions of Bison will not add the ';'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:555.84: warning: a ';' might be needed at the end of action code
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:555.84:     future versions of Bison will not add the ';'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:557.84: warning: a ';' might be needed at the end of action code
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:557.84:     future versions of Bison will not add the ';'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:559.82: warning: a ';' might be needed at the end of action code
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:559.82:     future versions of Bison will not add the ';'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:561.78: warning: a ';' might be needed at the end of action code
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:561.78:     future versions of Bison will not add the ';'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:563.76: warning: a ';' might be needed at the end of action code
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ffscript.ypp:563.76:     future versions of Bison will not add the ';'
5>Compiling...
5>lex.yy.cpp
5>y.tab.cpp
4>UB_ZeldaSprite.cpp
3>Generating Code...
5>.\src\parser\y.tab.cpp(1634) : warning C4065: switch statement contains 'default' but no 'case' labels
5>UB_ZQuestZScript.cpp
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/ByteCode.cpp(1925) : error C2084: function 'std::string OGetFFCScript::toString(void)' already has a body
5>        c:\users\dell\desktop\zc_2.54\2.54_merge\src\parser\ByteCode.h(2448) : see previous definition of 'toString'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/DataStructs.cpp(29) : warning C4018: '<' : signed/unsigned mismatch
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/DataStructs.cpp(50) : warning C4018: '<' : signed/unsigned mismatch
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/DataStructs.cpp(116) : warning C4018: '>' : signed/unsigned mismatch
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/DataStructs.cpp(170) : warning C4018: '>' : signed/unsigned mismatch
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/GlobalSymbols.cpp(2004) : error C2065: 'memberids' : undeclared identifier
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/GlobalSymbols.cpp(2020) : error C2065: 'memberids' : undeclared identifier
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/GlobalSymbols.cpp(2035) : error C2065: 'memberids' : undeclared identifier
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/GlobalSymbols.cpp(2050) : error C2065: 'memberids' : undeclared identifier
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/GlobalSymbols.cpp(3124) : error C2065: 'memberids' : undeclared identifier
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/GlobalSymbols.cpp(3139) : error C2065: 'memberids' : undeclared identifier
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/GlobalSymbols.cpp(3203) : error C2065: 'memberids' : undeclared identifier
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/Types.cpp(6) : error C2039: 'to_string' : is not a member of 'std'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/Types.cpp(6) : error C2873: 'to_string' : symbol cannot be used in a using-declaration
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/parser/Types.cpp(110) : error C3861: 'to_string': identifier not found
5>UB_ZQuestMisc.cpp
4>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/script_drawing.cpp(17) : warning C4005: 'DegtoFix' : macro redefinition
4>        C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/maps.cpp(43) : see previous definition of 'DegtoFix'
4>UB_ZeldaGUI.cpp
5>c:\users\dell\desktop\zc_2.54\2.54_merge\src\parser\Types.h(81) : error C2628: 'ZVarTypeSimple' followed by 'void' is illegal (did you forget a ';'?)
5>c:\users\dell\desktop\zc_2.54\2.54_merge\src\parser\Types.h(81) : error C2208: 'const ZVarTypeSimple' : no members defined using this type
5>c:\users\dell\desktop\zc_2.54\2.54_merge\src\parser\Types.h(92) : error C2059: syntax error : 'constant'
5>c:\users\dell\desktop\zc_2.54\2.54_merge\src\parser\Types.h(92) : error C2238: unexpected token(s) preceding ';'
5>c:\users\dell\desktop\zc_2.54\2.54_merge\src\zquestdat.h(10) : warning C4005: 'BMP_MOUSE' : macro redefinition
5>        c:\users\dell\desktop\zc_2.54\2.54_merge\src\zeldadat.h(7) : see previous definition of 'BMP_MOUSE'
5>UB_ZQuestGUI.cpp
4>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/backend/SFXBackend.cpp(5) : error C2062: type 'int' unexpected
4>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/backend/SFXBackend.cpp(5) : error C2062: type 'int' unexpected
4>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/backend/SFXBackend.cpp(5) : error C2059: syntax error : ')'
4>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/backend/SFXBackend.cpp(5) : error C2143: syntax error : missing ';' before '{'
4>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/backend/SFXBackend.cpp(5) : error C2447: '{' : missing function header (old-style formal list?)
4>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/backend/SFXBackend.cpp(6) : error C2062: type 'int' unexpected
4>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/backend/SFXBackend.cpp(6) : error C2062: type 'int' unexpected
4>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/backend/SFXBackend.cpp(6) : error C2059: syntax error : ')'
4>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/backend/SFXBackend.cpp(6) : error C2143: syntax error : missing ';' before '{'
4>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/backend/SFXBackend.cpp(6) : error C2447: '{' : missing function header (old-style formal list?)
4>UB_ZeldaCore.cpp
3>Compiling resources...
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/backend/SFXBackend.cpp(5) : error C2062: type 'int' unexpected
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/backend/SFXBackend.cpp(5) : error C2062: type 'int' unexpected
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/backend/SFXBackend.cpp(5) : error C2059: syntax error : ')'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/backend/SFXBackend.cpp(5) : error C2143: syntax error : missing ';' before '{'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/backend/SFXBackend.cpp(5) : error C2447: '{' : missing function header (old-style formal list?)
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/backend/SFXBackend.cpp(6) : error C2062: type 'int' unexpected
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/backend/SFXBackend.cpp(6) : error C2062: type 'int' unexpected
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/backend/SFXBackend.cpp(6) : error C2059: syntax error : ')'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/backend/SFXBackend.cpp(6) : error C2143: syntax error : missing ';' before '{'
5>C:/Users/DELL/Desktop/ZC_2.54/2.54_Merge/src/backend/SFXBackend.cpp(6) : error C2447: '{' : missing function header (old-style formal list?)
5>UB_ZQuestCore.cpp
3>Microsoft (R) Windows (R) Resource Compiler Version 6.0.5724.0
3>Copyright (C) Microsoft Corporation.  All rights reserved.
3>Linking...
3>al_gif.lib(algif.obj) : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance
3>Generating code
4>Generating Code...
3>Finished generating code
5>Generating Code...
3>al_gif.lib(algif.obj) : warning LNK4099: PDB 'vc80.pdb' was not found with 'libs\win32\al_gif.lib' or at 'C:\Users\DELL\Desktop\ZC_2.54\2.54_Merge\Release\vc80.pdb'; linking object as if no debug info
3>libpng.lib(pngtrans.obj) : warning LNK4099: PDB 'vc80.pdb' was not found with 'libs\win32\libpng.lib' or at 'C:\Users\DELL\Desktop\ZC_2.54\2.54_Merge\Release\vc80.pdb'; linking object as if no debug info
3>libpng.lib(pngget.obj) : warning LNK4099: PDB 'vc80.pdb' was not found with 'libs\win32\libpng.lib' or at 'C:\Users\DELL\Desktop\ZC_2.54\2.54_Merge\Release\vc80.pdb'; linking object as if no debug info
3>libpng.lib(png.obj) : warning LNK4099: PDB 'vc80.pdb' was not found with 'libs\win32\libpng.lib' or at 'C:\Users\DELL\Desktop\ZC_2.54\2.54_Merge\Release\vc80.pdb'; linking object as if no debug info
3>libpng.lib(pngwtran.obj) : warning LNK4099: PDB 'vc80.pdb' was not found with 'libs\win32\libpng.lib' or at 'C:\Users\DELL\Desktop\ZC_2.54\2.54_Merge\Release\vc80.pdb'; linking object as if no debug info
3>libjpgal.lib(encode.obj) : warning LNK4099: PDB 'vc80.pdb' was not found with 'libs\win32\libjpgal.lib' or at 'C:\Users\DELL\Desktop\ZC_2.54\2.54_Merge\Release\vc80.pdb'; linking object as if no debug info
3>loadpng.lib(loadpng.obj) : warning LNK4099: PDB 'vc80.pdb' was not found with 'libs\win32\loadpng.lib' or at 'C:\Users\DELL\Desktop\ZC_2.54\2.54_Merge\Release\vc80.pdb'; linking object as if no debug info
3>al_gif.lib(lzw.obj) : warning LNK4099: PDB 'vc80.pdb' was not found with 'libs\win32\al_gif.lib' or at 'C:\Users\DELL\Desktop\ZC_2.54\2.54_Merge\Release\vc80.pdb'; linking object as if no debug info
3>libpng.lib(pngrutil.obj) : warning LNK4099: PDB 'vc80.pdb' was not found with 'libs\win32\libpng.lib' or at 'C:\Users\DELL\Desktop\ZC_2.54\2.54_Merge\Release\vc80.pdb'; linking object as if no debug info
3>libpng.lib(pngwutil.obj) : warning LNK4099: PDB 'vc80.pdb' was not found with 'libs\win32\libpng.lib' or at 'C:\Users\DELL\Desktop\ZC_2.54\2.54_Merge\Release\vc80.pdb'; linking object as if no debug info
3>libpng.lib(pngread.obj) : warning LNK4099: PDB 'vc80.pdb' was not found with 'libs\win32\libpng.lib' or at 'C:\Users\DELL\Desktop\ZC_2.54\2.54_Merge\Release\vc80.pdb'; linking object as if no debug info
3>libpng.lib(pngset.obj) : warning LNK4099: PDB 'vc80.pdb' was not found with 'libs\win32\libpng.lib' or at 'C:\Users\DELL\Desktop\ZC_2.54\2.54_Merge\Release\vc80.pdb'; linking object as if no debug info
3>libpng.lib(pngwio.obj) : warning LNK4099: PDB 'vc80.pdb' was not found with 'libs\win32\libpng.lib' or at 'C:\Users\DELL\Desktop\ZC_2.54\2.54_Merge\Release\vc80.pdb'; linking object as if no debug info
3>libjpgal.lib(decode.obj) : warning LNK4099: PDB 'vc80.pdb' was not found with 'libs\win32\libjpgal.lib' or at 'C:\Users\DELL\Desktop\ZC_2.54\2.54_Merge\Release\vc80.pdb'; linking object as if no debug info
3>loadpng.lib(savepng.obj) : warning LNK4099: PDB 'vc80.pdb' was not found with 'libs\win32\loadpng.lib' or at 'C:\Users\DELL\Desktop\ZC_2.54\2.54_Merge\Release\vc80.pdb'; linking object as if no debug info
3>al_gif.lib(gif.obj) : warning LNK4099: PDB 'vc80.pdb' was not found with 'libs\win32\al_gif.lib' or at 'C:\Users\DELL\Desktop\ZC_2.54\2.54_Merge\Release\vc80.pdb'; linking object as if no debug info
3>libpng.lib(pngmem.obj) : warning LNK4099: PDB 'vc80.pdb' was not found with 'libs\win32\libpng.lib' or at 'C:\Users\DELL\Desktop\ZC_2.54\2.54_Merge\Release\vc80.pdb'; linking object as if no debug info
3>libpng.lib(pngrio.obj) : warning LNK4099: PDB 'vc80.pdb' was not found with 'libs\win32\libpng.lib' or at 'C:\Users\DELL\Desktop\ZC_2.54\2.54_Merge\Release\vc80.pdb'; linking object as if no debug info
3>libpng.lib(pngrtran.obj) : warning LNK4099: PDB 'vc80.pdb' was not found with 'libs\win32\libpng.lib' or at 'C:\Users\DELL\Desktop\ZC_2.54\2.54_Merge\Release\vc80.pdb'; linking object as if no debug info
3>libpng.lib(pngerror.obj) : warning LNK4099: PDB 'vc80.pdb' was not found with 'libs\win32\libpng.lib' or at 'C:\Users\DELL\Desktop\ZC_2.54\2.54_Merge\Release\vc80.pdb'; linking object as if no debug info
3>libpng.lib(pngwrite.obj) : warning LNK4099: PDB 'vc80.pdb' was not found with 'libs\win32\libpng.lib' or at 'C:\Users\DELL\Desktop\ZC_2.54\2.54_Merge\Release\vc80.pdb'; linking object as if no debug info
3>libjpgal.lib(io.obj) : warning LNK4099: PDB 'vc80.pdb' was not found with 'libs\win32\libjpgal.lib' or at 'C:\Users\DELL\Desktop\ZC_2.54\2.54_Merge\Release\vc80.pdb'; linking object as if no debug info
3>libjpgal.lib(jpgalleg.obj) : warning LNK4099: PDB 'vc80.pdb' was not found with 'libs\win32\libjpgal.lib' or at 'C:\Users\DELL\Desktop\ZC_2.54\2.54_Merge\Release\vc80.pdb'; linking object as if no debug info
3>loadpng.lib(regpng.obj) : warning LNK4099: PDB 'vc80.pdb' was not found with 'libs\win32\loadpng.lib' or at 'C:\Users\DELL\Desktop\ZC_2.54\2.54_Merge\Release\vc80.pdb'; linking object as if no debug info
3>Embedding manifest...
3>Build log was saved at "file://c:\Users\DELL\Desktop\ZC_2.54\2.54_Merge\romview.dir\Release\BuildLog.htm"
3>romview - 0 error(s), 24 warning(s)
5>Build log was saved at "file://c:\Users\DELL\Desktop\ZC_2.54\2.54_Merge\zquest.dir\Release\BuildLog.htm"
5>zquest - 25 error(s), 45 warning(s)
4>Build log was saved at "file://c:\Users\DELL\Desktop\ZC_2.54\2.54_Merge\zelda.dir\Release\BuildLog.htm"
4>zelda - 10 error(s), 1 warning(s)
========== Build: 3 succeeded, 2 failed, 1 up-to-date, 0 skipped ==========

**Comment by gwx** [comment]
We just fixed this up.
