### ISSUE TITLE
Crash in Guys.cpp

### ISSUE THREAD

**Issue by SyrianBallaS** [ZQuestClassic/ZQuestClassic#632]
Using "Bounds of Waterford" to reproduce this issue, there seems to be an access violation in the isflier function.
Doesn't look bounds checked. The guysbuf pointer looks to be invalid from accessing memory outside it's range.

At this screen if you beat all the enemies on it, collect an overworld key, leave the screen and return, it happens 100% of the time.

![image](https://user-images.githubusercontent.com/18649925/89743891-955ab500-da75-11ea-92fc-e60efd57da51.png)

I'll share a screen shot of were it happened and a core dump.
Platform is Windows 10.

![image](https://user-images.githubusercontent.com/18649925/89743866-5d537200-da75-11ea-8a47-2338efe11c86.png)

Mini-dump provided:
https://drive.google.com/file/d/1eHCTjU010BRSU1z8GGuDQj7JbVHxM_hb/view?usp=sharing

**Comment by connorjclark** [comment]
Can you give this a try in the latest alpha?
