### ISSUE TITLE
ZQuest UI Elements are Mangled

### ISSUE THREAD

**Issue by ZoriaRPG** [ZQuestClassic/ZQuestClassic#65]
The new UI code that DD added do not draw properly in some instances. Here is what Quest->Init Data displays for me:

http://timelord.insomnia247.nl/zc/zc_dev/Quest-Init-Data-Drawing_error1.png
http://timelord.insomnia247.nl/zc/zc_dev/Quest-Init-Data-Drawing_error2.png

**Comment by evouga** [comment]
Fixed now.
