### ISSUE TITLE
Port to Game Maker 8 and then Game Maker Studio 1.4

### ISSUE THREAD

**Issue by ghost** [ZQuestClassic/ZQuestClassic#657]
I currently have a DLL library format that would allow me to make basically any game 100% in dll code and using the built in libraries. There is actually a need for this for a separate project, at least with core engine. I don’t know whether you guys would want me to post the final port here or not to see, so that is why I opened this. I also might need help in a few spots to understand this massive code base. You guys are difficult to get a hold of. Thanks.

**Comment by ghost** [comment]
The primary usage of this in the end would be for wall entering mechanics, which is why it would be DLL. I suspect much of the bulk will vanish due to not needing to do as much timing and OpenGL stuff, but it might be nice to have a few pointers at some point.

**Comment by EmilyV99** [comment]
>You guys are difficult to get a hold of. Thanks.

We have a development discord, https://discord.gg/4FvwpKt
