### ISSUE TITLE
Parser: Internal ZScript Arrays Are Broken (Hard Crash)

### ISSUE THREAD

**Issue by ZoriaRPG** [ZQuestClassic/ZQuestClassic#68]
Using ADDASSIGN, MINUSASSIGN, or similar with internal ZScript arrys crashes ZC instantly.

Example:

Link->Misc[0]++; //This crashes ZC
Link->Misc[0] += 9; //This crashes ZC. 
Link->Misc[0] = 9; //This does not crash ZC

**Comment by ZoriaRPG** [comment]
At a guess, this is likely related to the revisions for setters and getters. You might be trying to set the array index value of something strange.

**Comment by evouga** [comment]
@gwx ZoriaRPG tells me that you are already in the process of tracking this down?

**Comment by gwx** [comment]
Yes. I just fixed the increment/decrement, now I'm going to test += and similar.

**Comment by gwx** [comment]
And fixing that was rather easy.
