### ISSUE TITLE
Issues with allegros magic main.

### ISSUE THREAD

**Issue by ghost** [ZQuestClassic/ZQuestClassic#7]
This is the error message I get. Which I get only once.
....\allegro/allegro/platform/alwin.h:49:86: error: conflicting declaration of C function 'int WinMain(void_, void_, char*, int)

**Comment by Gleeok** [comment]
No idea. Conflicts with what? where? Is subsystem:Windows set?

**Comment by ghost** [comment]
@Gleeok 
I'm guessing it has something to do with MinGW. Going to try swapping compilers tomorrow. Since I have MSVC compiler as well.
