### ISSUE TITLE
Found a solution to the midi playback through Allegro rawmidi API not working on Linux.

### ISSUE THREAD

**Issue by zoharion** [ZQuestClassic/ZQuestClassic#707]
Even by adding alsa_rawmidi_device = hw:1,0 in zc.cfg, the midi still doesn't work, that's because allegro has a if statement that counts how many errors the snd_rawmidi_write function returns, if those errors are more than 3 the midi will stop working altogether.So to fix this issue go to the ./allegro/src/unix/alsamidi.c:239 and remove the if statements of the static void alsa_rawmidi_output(int data) function, leaving only the snd_rawmidi_write one. So a recompilation of allegro is needed to fix this old issue.

**Comment by connorjclark** [comment]
We don't use the allegro 4 backends anymore, so closing.

**Comment by ZoriaRPG** [comment]
Thank frak. I am glad to see some of the AG4 audio backends dying, so that
the software can live. I would still like to see SID chip tune support
added, but this is a big deal.
