### ISSUE TITLE
Building with MSVC 2019?

### ISSUE THREAD

**Issue by connorjclark** [ZQuestClassic/ZQuestClassic#718]
Hello! I'm experimenting with porting ZC to the web via emscripten (I've already got `loadquest` mostly working). More on that another time. For now, I need help simply building the project on Windows.

`Windows 10 with MSVC 2016` is the latest way mentioned to build the project on Windows. Besides being rather noobish at C++ dev, I'm immediately lost here because I can't find any mention of [MSVC 2016](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0). I could try 2017, but first I wanted to see if using the latest version (MSVC 2019 Community edition) would work.

Cmake creates the projects files just fine:

![image](https://user-images.githubusercontent.com/4071474/122507291-c91b3b00-cfb4-11eb-9010-e8f202c2432a.png)
(I don't know what Unity means here, but I read somewhere that it's preferred)

![image](https://user-images.githubusercontent.com/4071474/122507056-5a3de200-cfb4-11eb-9c45-34d1a3613294.png)

But building gave me errors. Here is the output from trying to build "ALL_BUILD": https://gist.github.com/connorjclark/f3f8d6dd469fb50e4020e05776ad96b1#file-just-errors-txt (tons of warnings as expected, but also 26 errors)

Most errors are understandable to me, but odd (conflicting declarations of the same variables).

others seems off:
```
Error	C2660	'sprite_list::drawshadow': function does not take 2 arguments	zelda	C:\Users\cjamc\code\ZeldaClassic\src\maps.cpp	3620	

> guys.drawshadow(framebuf,get_bit(quest_rules,qr_TRANSSHADOWS)!=0,true);
```
(the referenced line of code clearly has 3 args, not 2. )

```
Error	C2737	'brokenOffset': const object must be initialized	zelda	C:\Users\cjamc\code\ZeldaClassic\src\script_drawing.cpp	10786	

>     const bool brokenOffset= ( (get_bit(extra_rules, er_BITMAPOFFSET)!=0) || (get_bit(quest_rules,qr_BITMAPOFFSETFIX)!=0) );
```
(the referenced line of code clearly initializes a value. Why is it calling it an object when its typed as bool?)
EDIT: replacing `quest_rules` with `extra_rules` stops the error from happening. weird.

... and others I have no idea about, linker issues :)

```
Error	LNK2019	unresolved external symbol "struct PACKFILE * __cdecl pack_fopen_password(char const *,char const *,char const *)" (?pack_fopen_password@@YAPAUPACKFILE@@PBD00@Z) referenced in function "struct OGGFILE * __cdecl load_ogg_file(char *)" (?load_ogg_file@@YAPAUOGGFILE@@PAD@Z)	zcsound	C:\Users\cjamc\code\ZeldaClassic\build\zcmusic.obj	1	
```

I also focused on just building the `zelda` project (instead of all), and got mostly the same errors.

Is there any path forward for using MSVC 2019? If not, what is the ideal OS to build on (I have access to anything)?

(I'm on Windows 10)

**Comment by SyrianBallaS** [comment]
I can build with both VS 2017 and 2019 (though not likely to be used soon)

It should build.
Make sure win_bison and win_flex are in the path and uncheck unity build (no idea what this is supposed to do).

The only branch I've built was 2.55.

The supported compiler is msvc 2008. There should be downloads in the ZC discord.

**Comment by connorjclark** [comment]
I disabled "Unity" and it worked.
