### ISSUE TITLE
Zelda classic does not run on win11

### ISSUE THREAD

**Issue by vaualbus** [ZQuestClassic/ZQuestClassic#728]
As the title said last beta version of ZC diud not run on win11, it cannot start by having the common "application cannot start error 0xc0000007b that mean that some of the dependency for which ZC is build is missing

**Comment by dxgldotorg** [comment]
Make sure to install the latest MSVC 2008 redistributable, especially if using the included DXGL ddraw.dll which ZoriaRPG compiled using MSVC 2008.

**Comment by vaualbus** [comment]
On this not, do we use of a lot of C/C++ CRT functions? Could be cool to avoid such problem to get rid of the CRT completely?

**Comment by dxgldotorg** [comment]
It appears the zelda.exe file doesn't use the CRT, but due to how DXGL is written it does depend on it.

Try the x86 version of the redist from https://www.microsoft.com/en-us/download/details.aspx?id=26368 which should fix the issue.

DXGL is a separate project from ZC, and is built in a different manner.

**Comment by dxgldotorg** [comment]
As a follow-up, I have brought the development version of DXGL back to a state where it is usable, and ZC Player 2.55 Alpha 98 is running fine for me.

I personally run ZC on the same build of DXGL that I'm currently working on.

**Comment by connorjclark** [comment]
The nightly releases should be self-contained at this point. Let us know if they don't work for you / require you to download random runtime dependencies.

https://github.com/ArmageddonGames/ZeldaClassic/releases
