### ISSUE TITLE
ROMView: ROM File Types Window is Almost Not Visible

### ISSUE THREAD

**Issue by ZoriaRPG** [ZQuestClassic/ZQuestClassic#74]
The UI element for ROM File Types displays all the way on the bottom-right, and in the default view, you can only see its titlebar.

Image:
http://timelord.insomnia247.nl/zc/zc_dev/romview_issue_3.png

There is no resolution option in the menus to fix this.

**Comment by ZoriaRPG** [comment]
The default output is also still nearly pure blue, but this may be from the lack of a palette loaded?

ROMView has not worked in so long, that I have forgotten how to do anything with it: We need romview.txt.

I still feel that RV needs to support .ZPL files.

**Comment by evouga** [comment]
That's strange, it wasn't doing that for me a bit ago. I'm traveling the next few days but I'll take a look when I get home.

> I still feel that RV needs to support .ZPL files.

Why? The point of Romview is to convert image assets from _outside_ ZQ into a tile set usable in ZQ. The palette you want to load is the one exported by your NES/SNES emulator... once you have an image or palette in ZQ format, there is no point loading it into Romview.

**Comment by evouga** [comment]
I'm not seeing this issue. Did you manually set some non-default screen resolution in ag.cfg?

Romview is using Allegro's centre_dialog() to position the window, which may not be working correctly at resolutions other than 320x240... I'll look into it if you give me more information about how to reproduce.

**Comment by ZoriaRPG** [comment]
All that i did, was run the exe, and select the menu option.

Here is my ag.cfg

[romview-graphics]
resx = 640
resy = 480
fullscreen = 0
native = 1

Running RV at this resolution causes the issue. Dropping to 320x240 does fix it. 
fps = 60

**Comment by evouga** [comment]
Fixed.
