### ISSUE TITLE
ZQuest: Windows 10 Fullscreen Issues Reported

### ISSUE THREAD

**Issue by ZoriaRPG** [ZQuestClassic/ZQuestClassic#75]
ZQuest is going to need a 24b double-blit, just as ZC has.

**Comment by evouga** [comment]
Can you elaborate? As far as I know there is currently no difference between ZC and ZQ's backend graphics code, other than the list of supported resolutions.

**Comment by evouga** [comment]
Closing pending a more specific report of what the issue is.
