### ISSUE TITLE
ZQuest: Init Data Not Setting

### ISSUE THREAD

**Issue by ZoriaRPG** [ZQuestClassic/ZQuestClassic#76]
If you set an item in init data, then change to another item and set its value, the value that you set for the prior item is not preserved. i.e. When the UI element refreshes to show the new selection, it is not maintaining prior settings changes. 

To replicate this, open the init data dialogue, select arrows, set wooden arrows true; then set bows, and set a short bow true.

Close the dialogue, and reopen it. Select arrows, and the arrow that you set will not be set, but the bow will.

This chains out to as many changes as you make. Only the last change is retained.

**Comment by evouga** [comment]
Fixed.
