### ISSUE TITLE
-savefile breaks with -standalone in 2.55 (works in 2.53)

### ISSUE THREAD

**Issue by fm3845w0** [ZQuestClassic/ZQuestClassic#771]
When launching a quest on Windows 7 through Zelda Classic 2.55, Alpha 102, Build 61 through the command line with the -standalone and -savefile switches, relaunching it throws the error, "This save file is for a different quest."

The same command line parameters work successfully with Zelda Classic 2.53.1, Beta 54, Build 33, suggesting this may be a regression in the code between then and now.

Is there a way to use standalone mode with per game save files through the command line on 2.55 Alpha 102 or later? If so, how should the command be formatted? If not, will this be fixed? If so, please indicate when it is fixed.

Thanks!

**Comment by connorjclark** [comment]
The latest release fixes this. https://github.com/ArmageddonGames/ZQuestClassic/releases/tag/nightly-2023-08-08

> Is there a way to use standalone mode with per game save files through the command line on 2.55 Alpha 102 or later? If so, how should the command be formatted? If not, will this be fixed? If so, please indicate when it is fixed.

Yup, there is now - see the release notes above.
