### ISSUE TITLE
Screen scaling

### ISSUE THREAD

**Issue by dxgldotorg** [ZQuestClassic/ZQuestClassic#792]
Consider adding screen scaling now that the game has been upgraded to Allegro 5.x which runs Direct3D or OpenGL.

**Comment by connorjclark** [comment]
Do you have an example of what this means in terms of the allegro 5 api?

**Comment by dxgldotorg** [comment]
Previously I had implemented within my DXGL library a means to perform 4:3 aspect corrected scaling for the game display (like the NES/SNES would appear on a TV of the time) however since my library only targets DirectDraw it no longer works.

Does Allegro 5 not have features to stretch game output to a display instead of having the 8:7 aspect?

**Comment by connorjclark** [comment]
I'm currently working on a refactor of the rendering code to handle scaling better.

**Comment by dxgldotorg** [comment]
> I'm currently working on a refactor of the rendering code to handle scaling better.

Do you by any chance plan on scaling to the desktop resolution?  Switching modes on recent Windows versions is particularly disruptive on multiple monitor environments.

**Comment by connorjclark** [comment]
Fullscreen is a flag that is off by default.

**Comment by ZoriaRPG** [comment]
In theory, this should not be an issue as the conversion of AG4 8bbp
bitmaps is converted to native screen depth OpenGL via the AL bitmap
handlers.

Thus you wouldn't have the flickering, tearing, or native display colour
depth drop issues.
