### ISSUE TITLE
ZQuest Windows Graphical Bug

### ISSUE THREAD

**Issue by ZoriaRPG** [ZQuestClassic/ZQuestClassic#80]
The 'Windows Button' in the taskbar is visible (often flickering) when running ZQuest in fullscreen mode, and it is not obscured by the black backdrop. Perhaps blitting a solid black layer might fix this.

**Comment by evouga** [comment]
Does the problem depend on the state of the native color mode checkbox?

**Comment by evouga** [comment]
Closing this as an Allegro/DirectDraw issue that cannot be fixed, pending further clarification.
