### ISSUE TITLE
Font rendering update breaks custom font on custom quest

### ISSUE THREAD

**Issue by fm3845w0** [ZQuestClassic/ZQuestClassic#861]
The nightly build from 2023-03-28 correctly renders the HUD font in Lost Isle.

The nightly build from 2023-03-29 breaks it, and reverts it to the default font.

The font is first visible on screen the moment you gain control of your character.

See changes:

https://github.com/ArmageddonGames/ZQuestClassic/compare/nightly-2023-03-28...nightly-2023-03-29

I request a reader cross-post this bug report to the PureZC Discord and forums.

**Comment by connorjclark** [comment]
Thanks for the detailed report.

> I request a reader cross-post this bug report to the PureZC Discord and forums.

That won't be necessary.

**Comment by fm3845w0** [comment]
Maybe it won't be if you're on the case. Thanks for the prompt response.

**Comment by connorjclark** [comment]
nightly-2023-03-28
![image](https://github.com/ZQuestClassic/ZQuestClassic/assets/4071474/d508fef2-7de8-4f81-91db-c08990bc413b)

nightly-2023-03-29
![image](https://github.com/ZQuestClassic/ZQuestClassic/assets/4071474/20bd0ba0-3662-4b92-8a64-a53a0ba1f215)

Confirmed still an issue.

**Comment by connorjclark** [comment]
This is fixed in latest nightly / Alpha 119.

https://github.com/ZQuestClassic/ZQuestClassic/commit/2bd4f84be75c808032ed3b5284148e990b5c13e4
