### ISSUE TITLE
Bug: Parser Cannot Typecase Array Indices

### ISSUE THREAD

**Issue by ZoriaRPG** [ZQuestClassic/ZQuestClassic#87]
Array indices no longer properly cast to ool.

If you do:

bool f(){
   int arr[3];
   arr[1] = 1;
   if ( arr[1] ) return true;
   return false;
}

The compiler will return an error: 'Cannot cast from float[] to bool'. Note the braces here. This is contrary to all ZScritpt syntax to date, and **must** be fixed.

**Comment by evouga** [comment]
Which changes broke this script?

**Comment by gwx** [comment]
Ah, I fixed this with 6a1e71f. Didn't see this issue here.
