### ISSUE TITLE
Running -standalone game.qst creates new save files each time while older progress isn't loaded

### ISSUE THREAD

**Issue by fm3845w0** [ZQuestClassic/ZQuestClassic#898]
**Goal:** I want to create Windows shortcuts for each qst file that bypass the file select, create a new save if none exists, and otherwise load the corresponding quest and save.

**Research:** The Player heading on Nightly 2023-08-08: "Previously, standalone mode only worked for a single quest file at a time. For example, run -standalone game.qst once and game.qst becomes the only quest that will work with the save file generated. Now, each quest will use a save file derived from the name of the quest file. You can also provide a specific path if you like. It will be resolved relative to the saves/ folder (you can also use an absolute path). Example usage: -standalone game.qst me.sav"

**Attempted solution:** I set the shortcut's "Start in" to "C:\PathToZC" and "Target" to "C:\PathToZC\zplayer.exe" -standalone "C:\PathToQuest\questname.qst"

**Expectation:** The first run of the shortcut creates in C:\PathToZC\saves a new file called questname.sav and later runs load this file.

**Problem:** The first run creates in C:\PathToZC\saves a new file formatted YYYY-MM-DD-questname-questname-qst.sav while for the 2nd and later runs it is YYYY-MM-DD-questname-questname-qst-XXX.sav where XXX starts at 002 and increments by 1 each run. Later runs do not load prior saves nor progress.

**More info:** This happens on a fresh install of 3.0 Prerelease 10 2023-12-02 on a new computer with unchanged settings, and happens whether Quickload Slot is set to Disabled or Slot 1. I save using the F6 menu in a running quest. When I input a save argument like "C:\PathToZC\zplayer.exe" -standalone "C:\PathToQuest\questname.qst" "C:\PathToZC\saves\savename.sav", savename does not appear in the file name of the save file which still reads YYYY-MM-DD-questname-questname-qst.sav or YYYY-MM-DD-questname-questname-qst-XXX.sav.

**Comment by connorjclark** [comment]
Thanks for the report! Fixed in https://github.com/ZQuestClassic/ZQuestClassic/commit/742115e11333df188997ce1dcf962246d1047d36 which will release in ~hour.
