### ISSUE TITLE
Feature request: shaders

### ISSUE THREAD

**Issue by fm3845w0** [ZQuestClassic/ZQuestClassic#899]
Lots like using shaders to upscale pixel art. For example:

**Before:** https://s.uvlist.net/l/y2006/1/13560.jpg
**After:** https://i.imgur.com/A8pSeVE.png

If implemented as a toggle, purists could keep them off, so everyone wins.

A project called librashader claims to simplify integration with projects:

https://github.com/SnowflakePowered/librashader

RetroArch has a non-librashader implementation:

https://github.com/libretro/common-shaders

**Comment by connorjclark** [comment]
Closing as not planned
