### ISSUE TITLE
Running zplayer with the params -standalone C:\PathToQst\game.qst then moving game.qst and running -standalone C:\NewPathToQst\game.qst throws error

### ISSUE THREAD

**Issue by fm3845w0** [ZQuestClassic/ZQuestClassic#901]
**Expectation:** zplayer searches C:\PathToZC\saves\ for standalone-game.sav then loads C:\NewPathToQst\game.qst with C:\PathToZC\saves\standalone-game.sav unless the user specifies an overriding save through -standalone C:\NewPathToQst\game.qst C:\PathToSave\savename.sav, in which case ZC loads savename.sav for only that session

**Problem:** zplayer throws the error "Invalid save file," saying "This save file is for a different quest."

**Why this matters:** Unless the quest path stays constant, the user can't:

- reorganize files
- migrate saves to a new computer
- get saves from someone
- send saves to someone

This is unintuitive. Name-matching qsts to savs gives control to the user in bypassing both the listed problems and those of hash-matching (where saves would break across quest versioning and during quest dev). This is probably why name-matching is the standard in emulators.

(Shout-outs to Connor, a rockstar of a dev in general, for making standalone mode work at all. It's mostly just usability left)

**Comment by EmilyV99** [comment]
Has nothing to do with standalone mode, this is a restriction with ALL save files.

**Comment by fm3845w0** [comment]
Thanks for the input Emily. That makes saves more worth reprogramming to emulation standards, since many more users will face the bulleted complications than if this only affected standalone mode.

**Comment by connorjclark** [comment]
This is fixed for next release.
