### ISSUE TITLE
Please compile z quest classic lower system requirements 

### ISSUE THREAD

**Issue by Shadowblitz16** [ZQuestClassic/ZQuestClassic#911]
I am on kubuntu 22.04 lts and can't use zelda classic because it's using cutting edge libraries.

My gcc and g++ versions are 11.4.0 at most and my cmake is 3.22.1

I have tried both running the prebuilt linux executable and building it myself which I cannot do because those packages have not been down streamed and probabaly will not be down streamed until the next lts version.

**Comment by connorjclark** [comment]
I'm not lowering the versions of software we use in our build to accommodate a specific system to build from source. You could upgrade your software beyond what the distro provides directly, no?

That said, [I am learning how to distribute on Linux](https://www.reddit.com/r/linuxquestions/comments/1all23n/im_a_developer_of_an_open_source_program_but_have/) and may have another solution sometime in the future. But for now, and possibly forever, the officially supported way to run on Linux is via [flatpak](https://flathub.org/apps/com.zquestclassic.ZQuest).

I should probably make that clear on the website.

**Comment by Shadowblitz16** [comment]
I really hope it's not forever.
