### ISSUE TITLE
Classic quests won't open in web player

### ISSUE THREAD

**Issue by dxgldotorg** [ZQuestClassic/ZQuestClassic#914]
The classic_1st through classic_5th used for 2.55.x and below (using the current web player) display "Error: Invalid quest file" when attempting to open them.

If the old builtin quests are in the same format as custom quests, it should be sime enough to interpret them as custom quests and play them as normal?

The files are in /quests/Z1 Recreations/ and /quests/Old Contest Winners/

**Comment by connorjclark** [comment]
fixed in https://github.com/ZQuestClassic/ZQuestClassic/commit/49b71a2a1fe9e571ded039192cd28d77d68c1820

will release later today

**Comment by dxgldotorg** [comment]
It lives!

![image](https://github.com/ZQuestClassic/ZQuestClassic/assets/7480507/2b4edaaf-867c-4d9c-9803-7348ed1de876)
