### ISSUE TITLE
ZQuest Minimap does not apply correctly to warp dialog box.

### ISSUE THREAD

**Issue by ghost** [ZQuestClassic/ZQuestClassic#920]
![Screenshot 2024-04-06 084412](https://github.com/ZQuestClassic/ZQuestClassic/assets/164894827/e321f892-fa81-42a6-a2c0-43bc6fddaec2)
![Screenshot 2024-04-06 110249](https://github.com/ZQuestClassic/ZQuestClassic/assets/164894827/9672ce6a-9028-4d59-b416-3a2cf149d7ca)
![Screenshot 2024-04-06 084232](https://github.com/ZQuestClassic/ZQuestClassic/assets/164894827/83bb97c4-aa16-4346-bf8c-2a1c86a4d808)

**Comment by EmilyV99** [comment]
Fixed ( https://github.com/ZQuestClassic/ZQuestClassic/commit/bc0c7ac8e105c4f16d02186b72e4aacc777af0fb )
