### ISSUE TITLE
Aquamentus, Gohma, Ganon, Digdoggers, and Dodongos Only run there script for one frame.

### ISSUE THREAD

**Issue by ghost** [ZQuestClassic/ZQuestClassic#929]
https://www.purezc.net/forums/index.php?showtopic=78810#entry1077433

**Comment by connorjclark** [comment]
Closing because already tracked on forums and discord.

**Comment by ghost** [comment]
Okay, My mistake I wasn't aware it was being tracked on the discord as well thanks for your help as always everyone!
