### ISSUE TITLE
Combo Paste Lag

### ISSUE THREAD

**Issue by SkyLizardGirl** [ZQuestClassic/ZQuestClassic#930]
In the Select Combo window, pasting a combo lags before the new combo appears.
This happens in Mystical Harps .qst

**Comment by EmilyV99** [comment]
That'd probably be it checking if it needs to ask you if you want to overwrite a combo being used by something; it has to loop through a bunch of stuff to check that.

If you don't care about those warnings (which are there to help you not accidentally paste over stuff that you need), you can disable them by turning off `Combo Protection` in `Etc->Options->Toggles`

**Comment by SkyLizardGirl** [comment]
Oh ok i will try this.

**Comment by SkyLizardGirl** [comment]
> That'd probably be it checking if it needs to ask you if you want to overwrite a combo being used by something; it has to loop through a bunch of stuff to check that.
> 
> If you don't care about those warnings (which are there to help you not accidentally paste over stuff that you need), you can disable them by turning off `Combo Protection` in `Etc->Options->Toggles`

Ok i did this, but,,  it is still doing it. Just tested,  It is still freezing before combo is pasted.

**Comment by connorjclark** [comment]
https://github.com/ZQuestClassic/ZQuestClassic/commit/5fd5fa503e2ae843cae8ecad2cc1c9e3290b65a7
