### ISSUE TITLE
ZQuest: FFCs mand Items Placed on the Screen Cannot be Positioned (with the mouse).

### ISSUE THREAD

**Issue by ZoriaRPG** [ZQuestClassic/ZQuestClassic#95]
Reported by Shadowblitz16.

Items placed on the screen in ZQuest cannot be moved. Reported and verified on Win builds.

I tried builds all the way back to 4-JUNE-2017, and every build had this issue. I do not6 know when it was introduced, but I did not touch screen items in a way that should be able to affect this, AFAIK.

I need to sleep before i delve into this. Can someone check a few older builds and back-track this one?

**Comment by gwx** [comment]
I've narrowed it to the range c45871f (good) .. ca6482f (bad). I'm having a lot of trouble compiling most of the commits in between though.

**Comment by ZoriaRPG** [comment]
This also affects ffcs: They cannot be repositioned with the mouse. 

I believe it stems from void doxypos() in zquest.cpp (line 6336). 

I also verified that changing the video mode (any) does not affect this. The issue affects items and ffcs in all 320/240 and 800/600 video modes, and in fullscreen/windowed. I cannot test 1600x1200 as it is larger than my display.

**Comment by evouga** [comment]
Fixed.
