### ISSUE TITLE
UtilVisitors does not compile

### ISSUE THREAD

**Issue by evouga** [ZQuestClassic/ZQuestClassic#99]
UtillVisitors line 40 has an illegal use of va_start with a reference type:

`va_start(args, error);`

> The restrictions that ISO C places on the second parameter to the va_start() macro in header are different in this International Standard. The parameter parmN is the identifier of the rightmost parameter in the variable parameter list of the function definition (the one just before the ...). If the parameter parmN is declared with a function, array, or reference type, or with a type that is not compatible with the type that results when passing an argument for which there is no parameter, the behavior is undefined.

Moreover the compiler now has dozens of warnings about incorrect use of class vs struct. Please fix these as well.

**Comment by gwx** [comment]
Fixed the vararg issue with 06a56a9c2265088435bbf135a3764bcbd7e7a795.

There is apparently no way to make gcc warn about struct/class mismatch, so I'd like to leave those to someone who can actually see the warnings.
